// Generated by tools/zugferd/gen_guard.py from the Mustang CLI jar 2.14.0;
// do not edit, rerun it (scripts/zugferd-corpus checks for drift).

// The nodes of the profile `basic-wl` (node 0: the root element), compiled
// from the Factur-X 1.0.07 XSD BASIC-WL, Factur-X Schematron BASIC-WL;
// src/zugferd/guard/write.typ describes them.

#import "lists.typ": (
  country-2, currency, document-type, guideline-3, note-subject, payment-means,
  tax-type, vat-category-2,
)

// The rule that forbids an empty leaf, or none.
#let empty = none

// @typstyle off
#let nodes = (
(n: 3, z: none, c: (
  "rsm:ExchangedDocumentContext": (1, 0, 1, 1, 1),
  "rsm:ExchangedDocument": (6, 1, 1, 1, 6),
  "rsm:SupplyChainTradeTransaction": (13, 2, 1, 1, 13),
)),
(n: 1, z: none, c: (
  "ram:BusinessProcessSpecifiedDocumentContextParameter": (2, 0, 0, 1, 2),
  "ram:GuidelineSpecifiedDocumentContextParameter": (4, 1, 1, 1, 4),
)),
(n: 1, z: none, c: (
  "ram:ID": ("s", 0, 1, 1, 3),
)),
("s", ("schemeID": (false, "IP-GUARD-05", none)), none, none, none, none),
(n: 1, z: none, c: (
  "ram:ID": (guideline-3, 0, 1, 1, 5, "BR-01"),
)),
("s", ("schemeID": (false, "IP-GUARD-05", none)), ("guideline-3", "FX-SCH-A-000026", none, false), none, none, none),
(n: 3, z: none, c: (
  "ram:ID": ("s", 0, 1, 1, 3, "BR-02"),
  "ram:TypeCode": (document-type, 1, 1, 1, 7, "BR-04"),
  "ram:IssueDateTime": (8, 2, 1, 1, 8),
  "ram:IncludedNote": (10, 3, 0, none, 10),
)),
("s", none, ("document-type", "FX-SCH-A-000023", none, false), none, none, none),
(n: 1, z: none, c: (
  "udt:DateTimeString": (none, 0, 1, 1, 9, "BR-03"),
)),
("s", ("format": ("FX-SCH-A-000021", none, ("date-format", "BR-03", none, false))), none, none, none, "IP-GUARD-08"),
(n: 1, z: none, c: (
  "ram:Content": ("s", 0, 1, 1, 11),
  "ram:SubjectCode": (note-subject, 1, 0, 1, 12),
)),
"s",
("s", none, ("note-subject", "FX-SCH-A-000162", none, false), none, none, none),
(n: 3, z: none, c: (
  "ram:ApplicableHeaderTradeAgreement": (14, 0, 1, 1, 14),
  "ram:ApplicableHeaderTradeDelivery": (41, 1, 1, 1, 41),
  "ram:ApplicableHeaderTradeSettlement": (47, 2, 1, 1, 47),
)),
(n: 2, z: none, c: (
  "ram:BuyerReference": ("s", 0, 0, 1, 11),
  "ram:SellerTradeParty": (15, 1, 1, 1, 15),
  "ram:BuyerTradeParty": (28, 2, 1, 1, 28),
  "ram:SellerTaxRepresentativeTradeParty": (37, 3, 0, 1, 37),
  "ram:BuyerOrderReferencedDocument": (40, 4, 0, 1, 40),
  "ram:ContractReferencedDocument": (40, 5, 0, 1, 40),
)),
(n: 2, z: none, c: (
  "ram:ID": ("s", 0, 0, none, 3),
  "ram:GlobalID": (none, 1, 0, none, 16),
  "ram:Name": ("s", 2, 1, 1, 11, "BR-06"),
  "ram:SpecifiedLegalOrganization": (17, 3, 0, 1, 17),
  "ram:PostalTradeAddress": (19, 4, 1, 1, 19, "BR-08"),
  "ram:URIUniversalCommunication": (21, 5, 0, 1, 21),
  "ram:SpecifiedTaxRegistration": (none, 6, 0, 2, 23),
)),
("s", ("schemeID": ("FX-SCH-A-000037", none, ("icd", "FX-SCH-A-000031", none, false))), none, none, none, none),
(n: 0, z: none, c: (
  "ram:ID": ("s", 0, 0, 1, 18),
  "ram:TradingBusinessName": ("s", 1, 0, 1, 11),
)),
("s", ("schemeID": (false, none, ("icd", "FX-SCH-A-000031", none, false))), none, none, none, none),
(n: 1, z: none, c: (
  "ram:PostcodeCode": ("s", 0, 0, 1, 11),
  "ram:LineOne": ("s", 1, 0, 1, 11),
  "ram:LineTwo": ("s", 2, 0, 1, 11),
  "ram:LineThree": ("s", 3, 0, 1, 11),
  "ram:CityName": ("s", 4, 0, 1, 11),
  "ram:CountryID": (country-2, 5, 1, 1, 20, "BR-09"),
  "ram:CountrySubDivisionName": ("s", 6, 0, 1, 11),
)),
("s", none, ("country-2", "FX-SCH-A-000036", none, false), none, none, none),
(n: 1, z: none, c: (
  "ram:URIID": (none, 0, 1, 1, 22, "BR-62"),
)),
("s", ("schemeID": ("FX-SCH-A-000037", none, ("eas-2", "FX-SCH-A-000031", none, false))), none, none, none, none),
(d: ("ram:ID", "@schemeID"), m: ("FC": 24, "VA": 26), o: "IP-GUARD-05", k: ("FC": (1, "FX-SCH-A-000034"), "VA": (1, "FX-SCH-A-000033"))),
(n: 1, z: none, c: (
  "ram:ID": (none, 0, 1, 1, 25),
)),
("s", ("schemeID": ("FX-SCH-A-000037", none, none)), none, none, none, none),
(n: 1, z: none, c: (
  "ram:ID": (none, 0, 1, 1, 27),
)),
("s", ("schemeID": ("FX-SCH-A-000037", none, none)), none, (("vat-prefix", "BR-CO-09", none, false), none), none, none),
(n: 2, z: none, c: (
  "ram:ID": ("s", 0, 0, 1, 3, none, "FX-SCH-A-000163"),
  "ram:GlobalID": (none, 1, 0, 1, 16, none, "FX-SCH-A-000164"),
  "ram:Name": ("s", 2, 1, 1, 11, "BR-07"),
  "ram:SpecifiedLegalOrganization": (29, 3, 0, 1, 29),
  "ram:PostalTradeAddress": (30, 4, 1, 1, 30, "BR-10"),
  "ram:URIUniversalCommunication": (31, 5, 0, 1, 31),
  "ram:SpecifiedTaxRegistration": (none, 6, 0, 1, 32, none, "FX-SCH-A-000166"),
)),
(n: 0, z: none, c: (
  "ram:ID": ("s", 0, 0, 1, 18),
  "ram:TradingBusinessName": ("IP-GUARD-05",),
)),
(n: 1, z: none, c: (
  "ram:PostcodeCode": ("s", 0, 0, 1, 11),
  "ram:LineOne": ("s", 1, 0, 1, 11),
  "ram:LineTwo": ("s", 2, 0, 1, 11),
  "ram:LineThree": ("s", 3, 0, 1, 11),
  "ram:CityName": ("s", 4, 0, 1, 11),
  "ram:CountryID": (country-2, 5, 1, 1, 20, "BR-11"),
  "ram:CountrySubDivisionName": ("s", 6, 0, 1, 11),
)),
(n: 1, z: none, c: (
  "ram:URIID": (none, 0, 1, 1, 22, "BR-63"),
)),
(d: ("ram:ID", "@schemeID"), m: ("FC": "FX-SCH-A-000031", "VA": 33), o: 35, k: (:)),
(n: 1, z: none, c: (
  "ram:ID": (none, 0, 1, 1, 34),
)),
("s", ("schemeID": ("FX-SCH-A-000037", none, ("tax-scheme", "FX-SCH-A-000031", none, false))), none, (("vat-prefix", "BR-CO-09", none, false), none), none, none),
(n: 1, z: none, c: (
  "ram:ID": (none, 0, 1, 1, 36),
)),
("s", ("schemeID": ("FX-SCH-A-000037", none, ("tax-scheme", "FX-SCH-A-000031", none, false))), none, none, none, none),
(n: 3, z: (v: (("ram:SpecifiedTaxRegistration", "VA", 1, "BR-56"),)), c: (
  "ram:ID": ("IP-GUARD-05",),
  "ram:GlobalID": ("IP-GUARD-05",),
  "ram:Name": ("s", 2, 1, 1, 11, "BR-18"),
  "ram:SpecifiedLegalOrganization": ("IP-GUARD-05",),
  "ram:PostalTradeAddress": (38, 4, 1, 1, 38, "BR-19"),
  "ram:URIUniversalCommunication": ("IP-GUARD-05",),
  "ram:SpecifiedTaxRegistration": (none, 6, 1, 1, 39, "FX-SCH-A-000169", "FX-SCH-A-000169"),
)),
(n: 1, z: none, c: (
  "ram:PostcodeCode": ("s", 0, 0, 1, 11),
  "ram:LineOne": ("s", 1, 0, 1, 11),
  "ram:LineTwo": ("s", 2, 0, 1, 11),
  "ram:LineThree": ("s", 3, 0, 1, 11),
  "ram:CityName": ("s", 4, 0, 1, 11),
  "ram:CountryID": (country-2, 5, 1, 1, 20, "BR-20"),
  "ram:CountrySubDivisionName": ("s", 6, 0, 1, 11),
)),
(d: ("ram:ID", "@schemeID"), m: ("FC": "FX-SCH-A-000031", "VA": 33), o: 35, k: (:)),
(n: 1, z: none, c: (
  "ram:IssuerAssignedID": ("s", 0, 1, 1, 3),
  "ram:FormattedIssueDateTime": ("IP-GUARD-05",),
)),
(n: 0, z: none, c: (
  "ram:ShipToTradeParty": (42, 0, 0, 1, 42),
  "ram:ActualDeliverySupplyChainEvent": (44, 1, 0, 1, 44),
  "ram:DespatchAdviceReferencedDocument": (40, 2, 0, 1, 40),
)),
(n: 0, z: none, c: (
  "ram:ID": ("s", 0, 0, 1, 3, none, "FX-SCH-A-000163"),
  "ram:GlobalID": (none, 1, 0, 1, 16, none, "FX-SCH-A-000164"),
  "ram:Name": ("s", 2, 0, 1, 11),
  "ram:SpecifiedLegalOrganization": ("IP-GUARD-05",),
  "ram:PostalTradeAddress": (43, 4, 0, 1, 43),
  "ram:URIUniversalCommunication": ("IP-GUARD-05",),
  "ram:SpecifiedTaxRegistration": ("IP-GUARD-05",),
)),
(n: 1, z: none, c: (
  "ram:PostcodeCode": ("s", 0, 0, 1, 11),
  "ram:LineOne": ("s", 1, 0, 1, 11),
  "ram:LineTwo": ("s", 2, 0, 1, 11),
  "ram:LineThree": ("s", 3, 0, 1, 11),
  "ram:CityName": ("s", 4, 0, 1, 11),
  "ram:CountryID": (country-2, 5, 1, 1, 20, "BR-57"),
  "ram:CountrySubDivisionName": ("s", 6, 0, 1, 11),
)),
(n: 1, z: none, c: (
  "ram:OccurrenceDateTime": (45, 0, 1, 1, 45),
)),
(n: 1, z: none, c: (
  "udt:DateTimeString": (none, 0, 1, 1, 46),
)),
("s", ("format": ("FX-SCH-A-000021", none, ("date-format", "FX-SCH-A-000022", none, false))), none, none, none, "IP-GUARD-08"),
(n: 3, z: (r: (("count", ("ram:InvoiceCurrencyCode",), "FX-SCH-A-000042"), ("count", ("ram:TaxCurrencyCode",), "FX-SCH-A-000192"), ("other", ("ram:InvoiceCurrencyCode", "ram:TaxCurrencyCode"), "IP-GUARD-05")), t: ("ram:ApplicableTradeTax": "vat-breakdown")), c: (
  "ram:CreditorReferenceID": ("s", 0, 0, 1, 3),
  "ram:PaymentReference": ("s", 1, 0, 1, 11),
  "ram:InvoiceCurrencyCode": (currency, 3, 1, 1, 48, "BR-05"),
  "ram:PayeeTradeParty": (49, 4, 0, 1, 49),
  "ram:SpecifiedTradeSettlementPaymentMeans": (50, 5, 0, none, 50),
  "ram:ApplicableTradeTax": (54, 6, 1, none, 54, "BR-CO-18"),
  "ram:BillingSpecifiedPeriod": (60, 7, 0, 1, 60),
  "ram:SpecifiedTradeAllowanceCharge": (none, 8, 0, none, 61),
  "ram:SpecifiedTradePaymentTerms": (71, 9, 0, 1, 71),
  "ram:SpecifiedTradeSettlementHeaderMonetarySummation": (72, 10, 1, 1, 72),
  "ram:InvoiceReferencedDocument": (81, 11, 0, none, 81),
)),
("s", none, ("currency", "FX-SCH-A-000040", none, false), none, none, none),
(n: 1, z: none, c: (
  "ram:ID": ("s", 0, 0, 1, 3, none, "FX-SCH-A-000163"),
  "ram:GlobalID": (none, 1, 0, 1, 16, none, "FX-SCH-A-000164"),
  "ram:Name": ("s", 2, 1, 1, 11, "FX-SCH-A-000030"),
  "ram:SpecifiedLegalOrganization": (29, 3, 0, 1, 29),
  "ram:PostalTradeAddress": ("IP-GUARD-05",),
  "ram:URIUniversalCommunication": ("IP-GUARD-05",),
  "ram:SpecifiedTaxRegistration": ("IP-GUARD-05",),
)),
(n: 1, z: none, c: (
  "ram:TypeCode": (payment-means, 0, 1, 1, 51, "BR-49"),
  "ram:PayerPartyDebtorFinancialAccount": (52, 1, 0, 1, 52),
  "ram:PayeePartyCreditorFinancialAccount": (53, 2, 0, 1, 53),
)),
("s", none, ("payment-means", "FX-SCH-A-000023", none, false), none, none, none),
(n: 1, z: none, c: (
  "ram:IBANID": ("s", 0, 1, 1, 3),
)),
(n: 0, z: none, c: (
  "ram:IBANID": ("s", 0, 0, 1, 3),
)),
(n: 4, z: none, c: (
  "ram:CalculatedAmount": ("d2", 0, 1, 1, 55, "BR-46"),
  "ram:TypeCode": (tax-type, 1, 1, 1, 56),
  "ram:ExemptionReason": ("s", 2, 0, 1, 11),
  "ram:BasisAmount": ("d2", 3, 1, 1, 57, "BR-45"),
  "ram:CategoryCode": (vat-category-2, 4, 1, 1, 58, "BR-47"),
  "ram:RateApplicablePercent": ("d", 7, 0, 1, 59),
)),
("d", ("currencyID": (false, "IP-GUARD-05", none)), none, none, (2, true, "BR-DEC-20"), none),
("s", none, ("tax-type", "FX-SCH-A-000023", none, false), none, none, none),
("d", ("currencyID": (false, "IP-GUARD-05", none)), none, none, (2, true, "BR-DEC-19"), none),
("s", none, ("vat-category-2", "FX-SCH-A-000179", none, false), none, none, none),
"d",
(n: 0, z: (y: ((("ram:StartDateTime", "ram:EndDateTime"), "BR-CO-19"),)), c: (
  "ram:StartDateTime": (45, 0, 0, 1, 45),
  "ram:EndDateTime": (45, 1, 0, 1, 45),
)),
(d: ("ram:ChargeIndicator", "udt:Indicator"), m: ("false": 62, "true": 68), o: "IP-GUARD-05", k: (:)),
(n: 3, z: (y: ((("ram:Reason", "ram:ReasonCode"), "BR-33"),), t: ("ram:CategoryTradeTax": "vat-allowance")), c: (
  "ram:ChargeIndicator": (63, 0, 1, 1, 63, "BR-66"),
  "ram:BasisAmount": ("d2", 2, 0, 1, 65),
  "ram:ActualAmount": ("d2", 3, 1, 1, 66, "BR-31"),
  "ram:Reason": ("s", 5, 0, 1, 11),
  "ram:CategoryTradeTax": (67, 6, 1, 1, 67),
)),
(n: 1, z: none, c: (
  "udt:Indicator": ("b", 0, 1, 1, 64),
)),
"b",
("d", ("currencyID": (false, "IP-GUARD-05", none)), none, none, (2, true, "BR-DEC-02"), none),
("d", ("currencyID": (false, "IP-GUARD-05", none)), none, none, (2, true, "BR-DEC-01"), none),
(n: 2, z: none, c: (
  "ram:CalculatedAmount": ("IP-GUARD-05",),
  "ram:TypeCode": (tax-type, 1, 1, 1, 56),
  "ram:ExemptionReason": ("IP-GUARD-05",),
  "ram:BasisAmount": ("IP-GUARD-05",),
  "ram:CategoryCode": (vat-category-2, 4, 1, 1, 58),
  "ram:RateApplicablePercent": ("d", 7, 0, 1, 59),
)),
(n: 3, z: (y: ((("ram:Reason", "ram:ReasonCode"), "BR-38"),), t: ("ram:CategoryTradeTax": "vat-charge")), c: (
  "ram:ChargeIndicator": (63, 0, 1, 1, 63, "BR-66"),
  "ram:BasisAmount": ("d2", 2, 0, 1, 69),
  "ram:ActualAmount": ("d2", 3, 1, 1, 70, "BR-36"),
  "ram:Reason": ("s", 5, 0, 1, 11),
  "ram:CategoryTradeTax": (67, 6, 1, 1, 67),
)),
("d", ("currencyID": (false, "IP-GUARD-05", none)), none, none, (2, true, "BR-DEC-06"), none),
("d", ("currencyID": (false, "IP-GUARD-05", none)), none, none, (2, true, "BR-DEC-05"), none),
(n: 0, z: none, c: (
  "ram:Description": ("s", 0, 0, 1, 11),
  "ram:DueDateDateTime": (45, 1, 0, 1, 45),
  "ram:DirectDebitMandateID": ("s", 2, 0, 1, 3),
)),
(n: 4, z: none, c: (
  "ram:LineTotalAmount": ("d2", 0, 1, 1, 73, "BR-12"),
  "ram:ChargeTotalAmount": ("d2", 1, 0, 1, 74),
  "ram:AllowanceTotalAmount": ("d2", 2, 0, 1, 75),
  "ram:TaxBasisTotalAmount": ("d2", 3, 1, 1, 76, "BR-13"),
  "ram:TaxTotalAmount": (none, 4, 0, 2, 77),
  "ram:GrandTotalAmount": ("d2", 5, 1, 1, 78, "BR-14"),
  "ram:TotalPrepaidAmount": ("d2", 6, 0, 1, 79),
  "ram:DuePayableAmount": ("d2", 7, 1, 1, 80, "BR-15"),
)),
("d", ("currencyID": (false, "IP-GUARD-05", none)), none, none, (2, true, "BR-DEC-09"), none),
("d", ("currencyID": (false, "IP-GUARD-05", none)), none, none, (2, true, "BR-DEC-11"), none),
("d", ("currencyID": (false, "IP-GUARD-05", none)), none, none, (2, true, "BR-DEC-10"), none),
("d", ("currencyID": (false, "IP-GUARD-05", none)), none, none, (2, true, "BR-DEC-12"), none),
("d", ("currencyID": ("FX-SCH-A-000046", none, none)), none, none, (2, false, "BR-DEC-13"), none),
("d", ("currencyID": (false, "IP-GUARD-05", none)), none, none, (2, true, "BR-DEC-14"), none),
("d", ("currencyID": (false, "IP-GUARD-05", none)), none, none, (2, true, "BR-DEC-16"), none),
("d", ("currencyID": (false, "IP-GUARD-05", none)), none, none, (2, true, "BR-DEC-18"), none),
(n: 1, z: none, c: (
  "ram:IssuerAssignedID": ("s", 0, 1, 1, 3, "BR-55"),
  "ram:FormattedIssueDateTime": (82, 1, 0, 1, 82),
)),
(n: 1, z: none, c: (
  "qdt:DateTimeString": (none, 0, 1, 1, 46),
)),
)
