// The write guard (G1 and G2): the serializer of the e-invoice XML, which
// checks every element against the guard tables of its profile while it
// writes it. `dict-to-xml` (../xml.typ) calls it; the tables of a profile
// load when the first invoice of the profile is written.
//
// The builder (build.typ) describes the document as a tree of dictionaries:
// keys are element names, `@name` keys attributes and the key `""` the text
// of an element with attributes; an array repeats its element, and `none`
// or a blank text leaves the element out. `write` writes this tree and, in
// the same pass, checks every element against the node of its position in
// the guard tables of the profile (<profile>.typ next to this file,
// generated by tools/zugferd/gen_guard.py from the official XSD and
// Schematron artefacts):
//
// - G1, structure: the profile's schema knows the element at its position
//   and does not mark it as not used there; it is in schema order and
//   number (maxOccurs and the Schematron's counts); every required element
//   is there, and only the attributes the schema allows.
// - G2, values: the lexical form of decimals, indicators and format 102
//   dates (calendar dates), the maximum number of decimals (BR-DEC-*), and
//   every code in the official code lists of its position.
//
// The XML does not depend on the checks: the serializer writes the same
// document whatever it finds and returns what it found as findings (see
// `_finding`), which process-zugferd turns into diagnostics (report.typ).
// An element the tables do not know is written unchecked, so that a draft
// shows it; its names are checked, so that the document stays well-formed
// for Typst's XML parser (G4).
//
// The tables. A node is an element at a position; a child names its node by
// index. A leaf node is its kind ("s" text, "d" decimal, "b" indicator, "x"
// binary) or an array (kind, attributes, code list, prefix list, decimals,
// date): attributes map a name to (required, the rule that marks it as not
// used here, code list); a code list is (name in lists.typ, rule, the codes
// other validators reject: their rule, compared in upper case); a prefix
// list is (code list, (attribute, value) it applies to); decimals are
// (maximum, counted as written, rule), and date is the rule of a format 102
// date. A complex node is a dictionary (n: number of required children, z:
// further checks or none, c: children). A child maps its name to (the rule
// that marks it as not used here,), or to (action, index in the schema's
// sequence, minimum, maximum or none, node, rule of the minimum, rule of the
// maximum; rules only as far as there are any). The action is the writer's
// fast path: the index of a complex node, which a dictionary value is
// written as; the class of plain texts that pass every check of the leaf by
// their form alone ("s" any text, "d" a decimal, "d2" a decimal with at most
// two decimals, "b" an indicator); the code list (of lists.typ) of a leaf
// whose only check it is; or `none`. An element the
// Schematron treats by the value of a discriminator (e.g. `ram:ID/@schemeID`
// of a tax registration) has a dispatch as its node: (d: discriminator path,
// m: value -> node or the rule that forbids it, o: node or rule of any other
// value, k: value -> (maximum, rule)). Further checks: `e` the rule that
// forbids an empty element, `v` minimum numbers of variants, `g` counts over
// paths, `y` children of which one is required, `x` children that exclude
// each other, `r` the currency cross references of the VAT total. Besides
// its `nodes`, the module of a profile has `empty`, the rule that forbids an
// empty leaf (XRechnung), or none.
//
// Performance (concept 6.4, budget 0.5 ms per invoice line): Typst memoizes
// every call of a closure and spends about a microsecond on a call of a
// function or method, less on an operator. So the writer makes one call per
// complex element and writes the common children (a plain text, a decimal)
// in its loop, tested with the `in` operator; it checks the order and number
// of the children with one memoized call on their names (`structure`),
// which elements of the same structure share, e.g. the lines of an invoice.
// A leaf with further checks goes through `_leaf`, memoized as well, so a
// code that repeats is checked once.

#import "../xml.typ": escaped-class, xml-escape
#import "../../utils/text.typ": plain-text
#import "lists.typ": lists as code-lists

// A text written as it is: not blank, and nothing `xml-escape` changes.
#let _plain = {
  let c = escaped-class
  regex("^[^" + c + "]*[^\\s" + c + "][^" + c + "]*$")
}
// Lexical space of xs:decimal without the whitespace the XSD collapses
// (the serializer never writes any): digits, at most one point, a sign.
#let _decimal = regex("^[+-]?(?:[0-9]+(?:\\.[0-9]*)?|\\.[0-9]+)$")
// The same with at most two decimals as written (fast class "d2").
#let _decimal2 = regex("^[+-]?(?:[0-9]+(?:\\.[0-9]{0,2})?|\\.[0-9]{1,2})$")
#let _booleans = ("true": true, "false": true, "1": true, "0": true)

// The patterns only rare paths need, compiled on their first use (a call
// without arguments is memoized): base64 data, and the names of elements and
// attributes the tables do not know. An element name has one of the
// prefixes the root declares; an attribute name none, or `xml` or `xmlns`.
#let _rare-patterns() = (
  base64: regex("^[A-Za-z0-9+/=\\s]*$"),
  element: regex("^(?:rsm|ram|udt|qdt):[A-Za-z_][A-Za-z0-9._-]*$"),
  attribute: regex(
    "^(?:(?:xml|xmlns):)?[A-Za-z_][A-Za-z0-9._-]*$",
  ),
)

// Days per month of a format 102 date; 29 February is checked separately.
#let _days = (31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)

// Whether `text` is eight digits (a decimal without sign or point).
#let _digits8(text) = (
  text.len() == 8
    and _decimal in text
    and not ("." in text or "+" in text or "-" in text)
)

/// Whether `text` is a calendar date in the format 102 (YYYYMMDD).
///
/// -> bool
#let valid-date-102(text) = {
  if type(text) != str or not _digits8(text) { return false }
  let year = int(text.slice(0, 4))
  let month = int(text.slice(4, 6))
  let day = int(text.slice(6, 8))
  if month < 1 or month > 12 or day < 1 or day > _days.at(month - 1) {
    return false
  }
  let leap = (
    calc.rem(year, 4) == 0
      and (calc.rem(year, 100) != 0 or calc.rem(year, 400) == 0)
  )
  month != 2 or day <= 28 or leap
}

/// The root element of every profile and the namespaces of its prefixes.
#let root-tag = "rsm:CrossIndustryInvoice"
#let namespaces = (
  "xmlns:rsm": "urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100",
  "xmlns:qdt": "urn:un:unece:uncefact:data:standard:QualifiedDataType:100",
  "xmlns:ram": "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100",
  "xmlns:udt": "urn:un:unece:uncefact:data:standard:UnqualifiedDataType:100",
)

// The namespace declarations the root may have: its prefixes and the XML
// Schema instance namespace.
#let _declarations = (
  namespaces + ("xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance")
)

/// The kinds of findings after which the XML may not be well-formed, so
/// that Typst's XML parser (G4) must not read it: an invalid name, a
/// missing namespace declaration, or not exactly one root element.
#let malformed-kinds = ("name", "namespace", "root")

// The entry of a child a node does not know, like the entry `(rule,)` of a
// child the profile does not use there.
#let _unknown = (none,)

// The tables of a profile: its nodes, and the rule that forbids an empty
// leaf (or none). Only the profile an invoice uses is loaded.
#let _tables(profile) = if profile == "minimum" {
  import "minimum.typ" as tables
  tables
} else if profile == "basic-wl" {
  import "basic-wl.typ" as tables
  tables
} else if profile == "basic" {
  import "basic.typ" as tables
  tables
} else if profile == "en16931" {
  import "en16931.typ" as tables
  tables
} else if profile == "xrechnung" {
  import "xrechnung.typ" as tables
  tables
} else { none }

// A problem the guard found: its kind, the official rule (or `none`, for
// which report.typ names the guard's own rule of the kind), the path of
// elements from the element that found it, and details.
#let _finding(kind, rule, path, ..details) = (
  (kind: kind, rule: rule, path: path) + details.named()
)

// Findings of the child `step` of the element `tag`: their paths from `tag`.
#let _lift(found, tag, step) = {
  let out = ()
  for f in found { out.push(f + (path: (tag, step) + f.path.slice(1))) }
  out
}

// The text of a written value.
#let _text(value) = if type(value) == str { value } else { plain-text(value) }

// An element without checks, for elements of no known position: the same
// output the checked writer produces.
#let _raw(tag, body) = {
  if body == none { return "" }
  if type(body) == array {
    let out = ""
    for item in body { out += _raw(tag, item) }
    return out
  }
  if type(body) == dictionary {
    let attrs = ""
    let children = ""
    for (key, value) in body {
      if key.starts-with("@") {
        if value != none {
          attrs += " " + key.slice(1) + "=\"" + xml-escape(value) + "\""
        }
      } else if key == "" {
        if type(value) == dictionary {
          for (k, v) in value { children += _raw(k, v) }
        } else if value != none {
          children += xml-escape(value)
        }
      } else {
        children += _raw(key, value)
      }
    }
    // An identifier or code without its value would be invalid.
    if "" in body and children.trim() == "" { return "" }
    return if children == "" {
      "<" + tag + attrs + " />"
    } else {
      "<" + tag + attrs + ">" + children + "</" + tag + ">"
    }
  }
  let value = xml-escape(body)
  if value.trim() == "" { return "" }
  "<" + tag + ">" + value + "</" + tag + ">"
}

// A finding when the attribute `name` of the element `tag` is no valid name.
#let _attribute-name(tag, name) = if (
  name.match(_rare-patterns().attribute) == none
) {
  (_finding("name", none, (tag,), value: name),)
} else { () }

// Names in an unchecked subtree that would break the document.
#let _bad-names(tag, body) = {
  let found = ()
  if tag.match(_rare-patterns().element) == none {
    found.push(_finding("name", none, (tag,), value: tag))
  }
  if type(body) == array {
    for item in body { found += _bad-names(tag, item) }
  } else if type(body) == dictionary {
    for (key, value) in body {
      if key.starts-with("@") {
        found += _attribute-name(tag, key.slice(1))
      } else if key == "" {
        if type(value) == dictionary {
          for (k, v) in value { found += _lift(_bad-names(k, v), tag, k) }
        }
      } else {
        found += _lift(_bad-names(key, value), tag, key)
      }
    }
  }
  found
}

// The number of decimals of a decimal: as written (`lexical`, the
// Schematron's `string-length(substring-after(., '.'))`), or of its value
// (trailing zeros do not count).
#let _decimals(text, lexical) = {
  let parts = text.split(".")
  if parts.len() < 2 { return 0 }
  let fraction = parts.at(1)
  if not lexical { fraction = fraction.trim("0", at: end, repeat: true) }
  fraction.len()
}

// `none` when `value` is in the code list `spec` = (name, rule, exceptions,
// upper case), else the rule to report. A list is a string of its codes,
// each between two spaces (see lists.typ).
#let _code-rule(value, spec) = {
  let (name, rule, exceptions, casefold) = spec
  let code = if casefold { upper(value) } else { value }
  if (
    code != ""
      and not code.contains(" ")
      and (" " + code + " ") in code-lists.at(name)
  ) { return none }
  if exceptions != none { exceptions.at(value, default: rule) } else { rule }
}

// Checks the text of a leaf against its array node; `attrs` are the
// attributes written.
#let _check-text(tag, text, node, attrs) = {
  let found = ()
  let (kind, _, list, prefix, fraction, date) = node
  if kind == "d" and text.match(_decimal) == none {
    found.push(_finding(
      "lexical",
      none,
      (tag,),
      value: text,
      expected: "a decimal",
    ))
  } else if kind == "b" and text not in _booleans {
    found.push(_finding(
      "lexical",
      none,
      (tag,),
      value: text,
      expected: "an indicator",
    ))
  } else if kind == "x" and text.match(_rare-patterns().base64) == none {
    found.push(_finding(
      "lexical",
      none,
      (tag,),
      value: text,
      expected: "base64 data",
    ))
  }
  if fraction != none and kind == "d" {
    let (limit, lexical, rule) = fraction
    if _decimals(text, lexical) > limit {
      found.push(_finding("fraction", rule, (tag,), value: text, limit: limit))
    }
  }
  if date != none and attrs.at("format", default: none) == "102" {
    if not valid-date-102(text) {
      // Eight digits that are no calendar date pass the official check
      // (CII-DT-097), but name no day: the guard's own rule.
      let rule = if _digits8(text) { "IP-GUARD-08" } else { date }
      found.push(_finding("date", rule, (tag,), value: text))
    }
  }
  if list != none {
    let rule = _code-rule(text, list)
    if rule != none {
      found.push(_finding("code", rule, (tag,), value: text, list: list.at(0)))
    }
  }
  if prefix != none {
    let (spec, when) = prefix
    if when == none or attrs.at(when.at(0), default: none) == when.at(1) {
      let characters = text.codepoints()
      let first = if characters == () { "" } else {
        characters.slice(0, calc.min(2, characters.len())).join()
      }
      let rule = _code-rule(first, spec)
      if rule != none {
        found.push(_finding(
          "prefix",
          rule,
          (tag,),
          value: first,
          list: spec.at(0),
        ))
      }
    }
  }
  found
}

// Checks the attributes of a leaf against its array node: `attrs` are the
// attributes written, with their texts.
#let _check-attributes(tag, node, attrs) = {
  let found = ()
  let specs = node.at(1)
  for (name, value) in attrs {
    let spec = if specs == none { none } else { specs.at(name, default: none) }
    if spec == none {
      found.push(_finding("attribute", none, (tag,), name: name))
      found += _attribute-name(tag, name)
      continue
    }
    if spec.at(1) != none {
      found.push(_finding("attribute-not-used", spec.at(1), (tag,), name: name))
    }
    if spec.at(2) != none {
      let rule = _code-rule(value, spec.at(2))
      if rule != none {
        found.push(_finding(
          "code",
          rule,
          (tag,),
          value: value,
          name: name,
          list: spec.at(2).at(0),
        ))
      }
    }
  }
  if specs != none {
    for (name, spec) in specs {
      if spec.at(0) != false and name not in attrs {
        let rule = if spec.at(0) == true { none } else { spec.at(0) }
        found.push(_finding("attribute-missing", rule, (tag,), name: name))
      }
    }
  }
  found
}

// A leaf: the element `tag` with its text and attributes, checked against
// its node (a kind or an array); `empty` is the rule of the profile that
// forbids an empty leaf, or none. Returns (XML, findings).
#let _leaf(tag, body, node, empty) = {
  if type(node) == str { node = (node, none, none, none, none, none) }
  if type(body) != dictionary {
    let text = if type(body) == str { body } else { plain-text(body) }
    let escaped = if _plain in text { text } else { xml-escape(text) }
    if escaped.trim() == "" { return ("", ()) }
    return (
      "<" + tag + ">" + escaped + "</" + tag + ">",
      _check-text(tag, text, node, (:)) + _check-attributes(tag, node, (:)),
    )
  }
  // Attributes and text, written as `_raw` writes them.
  let attrs = (:)
  let written = ""
  let children = ""
  let text = none
  let found = ()
  for (key, value) in body {
    if key.starts-with("@") {
      if value != none {
        let name = key.slice(1)
        let v = if type(value) == str { value } else { plain-text(value) }
        written += (
          " "
            + name
            + "=\""
            + if _plain in v { v } else { xml-escape(v) }
            + "\""
        )
        attrs.insert(name, v)
      }
    } else if key == "" {
      if type(value) == dictionary {
        for (k, v) in value {
          let r = _raw(k, v)
          if r != "" {
            children += r
            found.push(_finding("unknown", none, (tag, k)))
            found += _lift(_bad-names(k, v), tag, k)
          }
        }
      } else if value != none {
        text = if type(value) == str { value } else { plain-text(value) }
        children += if _plain in text { text } else { xml-escape(text) }
      }
    } else {
      let r = _raw(key, value)
      if r != "" {
        children += r
        found.push(_finding("unknown", none, (tag, key)))
        found += _lift(_bad-names(key, value), tag, key)
      }
    }
  }
  if "" in body and children.trim() == "" { return ("", ()) }
  found += _check-attributes(tag, node, attrs)
  if children == "" {
    // An element without text: its text is checked as empty (no decimal,
    // no code), and a rule of the profile may forbid empty elements.
    if empty != none { found.push(_finding("empty", empty, (tag,))) }
    found += _check-text(tag, "", node, attrs)
    return ("<" + tag + written + " />", found)
  }
  if text != none { found += _check-text(tag, text, node, attrs) }
  ("<" + tag + written + ">" + children + "</" + tag + ">", found)
}

// The value of a discriminator path, e.g. ("ram:ID", "@schemeID"), in the
// tree of an element: a string, or `none`.
#let _discriminator(body, path) = {
  let value = body
  for step in path {
    if type(value) != dictionary { return none }
    value = value.at(step, default: none)
  }
  if type(value) == dictionary { value = value.at("", default: none) }
  if value == none or type(value) == array or type(value) == dictionary {
    return none
  }
  _text(value)
}

// Whether a subtree is written (the serializer leaves out `none`, blank text
// and elements with a blank value).
#let _present(value) = {
  if value == none { return false }
  if type(value) == array {
    for item in value { if _present(item) { return true } }
    return false
  }
  if type(value) == dictionary {
    if "" not in value { return true }
    let text = value.at("")
    if type(text) == dictionary { return text.values().any(_present) }
    return text != none and xml-escape(text).trim() != ""
  }
  xml-escape(value).trim() != ""
}

// The written elements at a path of child elements below a tree.
#let _values(body, path) = {
  let level = (body,)
  for step in path {
    let next = ()
    for item in level {
      if type(item) != dictionary { continue }
      let value = item.at(step, default: none)
      if type(value) == array {
        for v in value { if _present(v) { next.push(v) } }
      } else if _present(value) { next.push(value) }
    }
    level = next
  }
  level
}

// The further checks of a complex node (`z`) on the values of its tree:
// `v`, `g` and `r` (`structure` in `write` does the others).
#let _further-checks(tag, body, z, variants) = {
  let found = ()
  for (key, value, low, rule) in z.at("v", default: ()) {
    if variants.at(key, default: (:)).at(value, default: 0) < low {
      found.push(_finding("variant-min", rule, (tag, key), variant: value))
    }
  }
  for (path, low, high, rule) in z.at("g", default: ()) {
    let count = _values(body, path).len()
    if count < low or (high != none and count > high) {
      found.push(_finding(
        "aggregate",
        rule,
        (tag,),
        steps: path,
        count: count,
        low: low,
        high: high,
      ))
    }
  }
  for (kind, refs, rule) in z.at("r", default: ()) {
    // The VAT total (BT-110, BT-111) by the currency it is stated in: one
    // in each currency the settlement names, and no other.
    let currencies = ()
    for ref in refs {
      let value = body.at(ref, default: none)
      if value != none { currencies.push(_text(value)) }
    }
    let totals = ()
    for total in _values(body, (
      "ram:SpecifiedTradeSettlementHeaderMonetarySummation",
      "ram:TaxTotalAmount",
    )) {
      let currency = if type(total) == dictionary {
        total.at("@currencyID", default: none)
      }
      totals.push(if currency == none { none } else { _text(currency) })
    }
    if kind == "count" {
      for currency in currencies {
        let n = 0
        for c in totals { if c == currency { n += 1 } }
        if n > 1 {
          found.push(_finding(
            "xref-count",
            rule,
            (tag,),
            value: currency,
            count: n,
          ))
        }
      }
    } else {
      for currency in totals {
        if currency not in currencies {
          found.push(_finding("xref-other", rule, (tag,), value: currency))
        }
      }
    }
  }
  found
}

/// Serializes the builder's element tree `data` and checks it against the
/// guard tables of `profile` in the same pass (see `dict-to-xml`).
///
/// -> dictionary
#let write(data, profile) = {
  let tables = _tables(profile)
  if tables == none {
    panic("no guard tables for the profile " + repr(profile))
  }
  let nodes = tables.nodes
  let empty = tables.empty
  if data == none { data = (:) }
  if type(data) != dictionary {
    panic(
      "dict-to-xml expects a dictionary of the root element, got " + repr(data),
    )
  }

  // The checks on the names of the children an element `tag` of the node
  // `id` writes: their order and number, the required children, and the
  // further checks on names (`e`, `y`, `x`). The children written are the
  // `keys` of the element's tree that the node allows, except the `skipped`
  // ones (nothing written), each once unless `counts` says otherwise. Typst
  // memoizes the call, so that elements of the same structure, e.g. the
  // lines of an invoice, are checked once.
  let structure(id, tag, keys, skipped, counts) = {
    let node = nodes.at(id)
    let children = node.c
    let found = ()
    let last = -1
    let required = 0
    let written = 0
    for key in keys {
      let spec = children.at(key, default: _unknown)
      if spec.len() == 1 or key in skipped { continue }
      written += 1
      let count = if key in counts { counts.at(key) } else { 1 }
      let (_, index, low, high, _, ..rules) = spec
      if index < last { found.push(_finding("order", none, (tag, key))) }
      last = index
      if low > 0 { required += 1 }
      if high != none and count > high {
        found.push(_finding(
          "max",
          rules.at(1, default: none),
          (tag, key),
          count: count,
          limit: high,
        ))
      }
    }
    // Whether the element writes the child `key` the node allows.
    let present(key) = key in keys and key not in skipped
    if required < node.n {
      for (key, spec) in children {
        if spec.len() > 1 and spec.at(2) > 0 and not present(key) {
          found.push(_finding("min", spec.at(5, default: none), (tag, key)))
        }
      }
    }
    let z = node.z
    if z != none {
      for (tags, rule) in z.at("y", default: ()) {
        if not tags.any(present) {
          found.push(_finding("any-of", rule, (tag,), tags: tags))
        }
      }
      for (tags, rule) in z.at("x", default: ()) {
        if tags.all(present) {
          found.push(_finding("exclusive", rule, (tag,), tags: tags))
        }
      }
      if "e" in z and written == 0 {
        found.push(_finding("empty", z.e, (tag,)))
      }
    }
    found
  }

  // An element of a complex node. Returns (XML, findings).
  let element(tag, body, id) = {
    let node = nodes.at(id)
    let children = node.c
    let out = ""
    let attrs = ""
    let found = ()
    // The children the node allows that are not written, or written other
    // than once (see `structure`).
    let skipped = ()
    let counts = (:)
    let variants = (:)
    for (key, value) in body {
      let spec = children.at(key, default: _unknown)
      let action = spec.first()
      let t = type(value)
      if t == str {
        // A leaf that a plain text of its form satisfies: a text, a decimal,
        // an indicator, or a code of its list (a code has no space and
        // nothing to escape).
        if (
          action == "s" and _plain in value
            or action == "d2" and _decimal2 in value
            or action == "d" and _decimal in value
            or action == "b" and value in _booleans
            or (
              type(action) == str
                and " " in action
                and not (" " in value)
                and (" " + value + " ") in action
            )
        ) {
          out += "<" + key + ">" + value + "</" + key + ">"
          continue
        }
      } else if t == dictionary and type(action) == int {
        let (xml, f) = element(key, value, action)
        if f != () { found += _lift(f, tag, key) }
        if xml == "" { skipped.push(key) } else { out += xml }
        continue
      }
      if spec.len() > 1 {
        if value == none {
          skipped.push(key)
          continue
        }
        // Everything else: repeated elements, variants, leaves with further
        // checks or attributes, other values.
        let target = spec.at(4)
        let n = nodes.at(target)
        let many = t == array
        let items = if many { value } else { (value,) }
        let count = 0
        let i = 0
        for item in items {
          i += 1
          if item == none { continue }
          let child = target
          if type(n) == dictionary and "d" in n {
            // The node of the variant, by the value of the discriminator.
            let v = _discriminator(item, n.d)
            let variant = if v != none and v in n.m { v } else { "*" }
            child = if variant == "*" { n.o } else { n.m.at(variant) }
            let seen = variants.at(key, default: (:))
            seen.insert(variant, seen.at(variant, default: 0) + 1)
            variants.insert(key, seen)
          }
          let (xml, f) = if type(child) == str {
            // A variant the profile does not use.
            let w = _raw(key, item)
            if w == "" { ("", ()) } else {
              (
                w,
                (_finding("not-used", child, (key,)),) + _bad-names(key, item),
              )
            }
          } else if type(nodes.at(child)) != dictionary {
            _leaf(key, item, nodes.at(child), empty)
          } else if type(item) == dictionary {
            element(key, item, child)
          } else {
            // Text where the schema expects elements.
            let w = _raw(key, item)
            (w, if w == "" { () } else { (_finding("text", none, (key,)),) })
          }
          if f != () {
            found += _lift(f, tag, if many { key + "[" + str(i) + "]" } else {
              key
            })
          }
          if xml == "" { continue }
          out += xml
          count += 1
        }
        if count == 0 { skipped.push(key) } else if count != 1 {
          counts.insert(key, count)
        }
        if type(n) == dictionary and "k" in n {
          for (v, limit) in n.k {
            let c = variants.at(key, default: (:)).at(v, default: 0)
            if c > limit.at(0) {
              found.push(_finding(
                "variant-max",
                limit.at(1),
                (tag, key),
                variant: v,
                count: c,
                limit: limit.at(0),
              ))
            }
          }
        }
      } else if value != none {
        if key.starts-with("@") {
          // No complex element of the schema has attributes; the root
          // declares the namespaces.
          let name = key.slice(1)
          attrs += " " + name + "=\"" + xml-escape(value) + "\""
          if id != 0 or name not in _declarations {
            found.push(_finding("attribute", none, (tag,), name: name))
            found += _attribute-name(tag, name)
          }
        } else if key == "" {
          // Text between the elements.
          if type(value) == dictionary {
            for (k, v) in value {
              out += _raw(k, v)
              found += _lift(_bad-names(k, v), tag, k)
            }
          } else { out += xml-escape(value) }
          found.push(_finding("text", none, (tag,)))
        } else {
          // Unknown here, or not used in the profile at this position (the
          // rule that says so).
          let r = _raw(key, value)
          if r != "" {
            out += r
            found.push(if action == none {
              _finding("unknown", none, (tag, key))
            } else {
              _finding("not-used", action, (tag, key))
            })
            found += _lift(_bad-names(key, value), tag, key)
          }
        }
      }
    }
    let problems = structure(id, tag, body.keys(), skipped, counts)
    if problems != () { found += problems }
    let z = node.z
    if z != none and ("v" in z or "g" in z or "r" in z) {
      found += _further-checks(tag, body, z, variants)
    }
    if "" in body and out.trim() == "" { return ("", found) }
    (
      if out == "" { "<" + tag + attrs + " />" } else {
        "<" + tag + attrs + ">" + out + "</" + tag + ">"
      },
      found,
    )
  }

  let xml = ""
  let findings = ()
  for (tag, body) in data {
    if body == none { continue }
    if tag != root-tag or type(body) != dictionary {
      // A second root, or text: the XML is no document of the schema.
      let r = _raw(tag, body)
      if r != "" {
        xml += r
        findings.push(_finding("root", none, (tag,), value: tag))
        findings += _bad-names(tag, body)
      }
      continue
    }
    for (name, uri) in namespaces {
      if body.at("@" + name, default: none) != uri {
        findings.push(_finding(
          "namespace",
          none,
          (tag,),
          name: name,
          value: uri,
        ))
      }
    }
    let (x, f) = element(tag, body, 0)
    xml += x
    findings += f
  }
  if xml.trim() == "" or data.at(root-tag, default: none) == none {
    findings.push(_finding("root", none, (root-tag,), missing: true))
  }
  (xml: xml, findings: findings)
}
