// The write guard (G1 and G2): the serializer of the e-invoice XML, which
// checks every element against the guard tables of its profile while it
// writes it. `dict-to-xml` (../xml.typ) calls it; the tables of a profile
// load when the first invoice of the profile is written.
//
// The builder (build.typ) describes the document as a tree of dictionaries:
// keys are element names, `@name` keys attributes and the key `""` the text
// of an element with attributes; an array repeats its element, and `none`
// or a blank text leaves the element out. `write` writes this tree and, in
// the same pass, checks every element against the node of its position in
// the guard tables of the profile (<profile>.json next to this file,
// generated by tools/zugferd/gen_guard.py from the official XSD and
// Schematron artefacts):
//
// - G1, structure: the profile's schema knows the element at its position
//   and does not mark it as not used there; it is in schema order and
//   number (maxOccurs and the Schematron's counts); every required element
//   is there with its text (a leaf without text counts as missing), and
//   only the attributes the schema allows.
// - G2, values: the lexical form of decimals, indicators and format 102
//   dates (calendar dates), the maximum number of decimals (BR-DEC-*),
//   every code in the official code lists of its position, and on a tax
//   element what its VAT category requires of its rate, VAT amount and
//   exemption reason (e.g. BR-S-05, BR-E-10).
//
// The XML does not depend on the checks: the serializer writes the same
// document whatever it finds and returns what it found as findings (see
// `_finding`), which process-zugferd turns into diagnostics (report.typ).
// An element the tables do not know is written unchecked, so that a draft
// shows it; its names are checked, so that the document stays well-formed
// for Typst's XML parser (G4). What only such elements need is in rare.typ,
// which loads when the first one is met.
//
// The tables (JSON: `nodes`, and `empty`, the rule that forbids an empty
// leaf, or null). A node is an element at a position; a child names its
// node by index. A leaf node is its kind ("s" text, "d" decimal, "b"
// indicator, "x" binary) or an array [kind, attributes, code list, prefix
// list, decimals, date]: attributes map a name to [required, the rule that
// marks it as not used here, code list]; a code list is [name in lists.typ,
// rule, the codes other validators reject: their rule, compared in upper
// case]; a prefix list is [code list, [attribute, value] it applies to];
// decimals are [maximum, counted as written, rule], and date is the rule of
// a format 102 date. A complex node is an object {n: number of required
// children, z: further checks, u: the children the profile does not use
// here, each with the rule that says so, c: the children} (z and u only
// when there are any). A child maps its name to [action, index in the
// schema's sequence, minimum, maximum or null, node, rules]: the rules of the
// minimum and the maximum, as far as there are any, or null. The action is
// the writer's fast path: the index of a complex node, which a dictionary
// value is written as; the class of plain texts that pass every check of the
// leaf by their form alone ("s" any text, "d" a decimal, "d2" a decimal with
// at most two decimals, "b" an indicator); the name of the code list (of
// lists.typ) of a leaf whose only check it is; or null. An element the
// Schematron treats by the value of a discriminator (e.g. `ram:ID/@schemeID`
// of a tax registration) has a dispatch as its node: {d: discriminator path,
// m: value -> node or the rule that forbids it, o: node or rule of any other
// value, k: value -> [maximum, rule]}. Further checks: `e` the rule that
// forbids an empty element, `v` minimum numbers of variants, `g` counts over
// paths, `y` children of which one is required, `x` children that exclude
// each other, `r` the currency cross references of the VAT total, `t` the
// tax elements among the children, each with the name of the table of the
// rules of the VAT categories where it is (`vat-rules` of lists.typ): per
// category code, (check, value, rule) of the rate, the VAT amount and the
// exemption reason.
//
// Performance (concept 6.4, budget 0.5 ms per invoice line): Typst memoizes
// every call of a closure, hashing its arguments, and spends about a
// microsecond on a call of a function or method, a fraction of that on an
// operator or a field access. So the writer makes one call per complex
// element and writes the common children (a plain text, a decimal, a code)
// in its loop, tested with operators; it checks the order and number of the
// children in the same loop, as it writes them. A leaf with further checks
// goes through `_leaf`, memoized, so a leaf that repeats is checked once.

#import "../xml.typ": escaped-class, xml-escape
#import "../../utils/text.typ": plain-text
#import "lists.typ": lists as code-lists, vat-rules

// A text written as it is: not blank, and nothing `xml-escape` changes.
#let _plain = {
  let c = escaped-class
  regex("^[^" + c + "]*[^\\s" + c + "][^" + c + "]*$")
}
// Lexical space of xs:decimal without the whitespace the XSD collapses
// (the serializer never writes any): digits, at most one point, a sign.
#let _decimal = regex("^[+-]?(?:[0-9]+(?:\\.[0-9]*)?|\\.[0-9]+)$")
// The same with at most two decimals as written (fast class "d2").
#let _decimal2 = regex("^[+-]?(?:[0-9]+(?:\\.[0-9]{0,2})?|\\.[0-9]{1,2})$")
// A decimal whose value is zero, in any of its lexical forms.
#let _zero = regex("^[+-]?(?:0+(?:\\.0*)?|\\.0+)$")
#let _booleans = ("true": true, "false": true, "1": true, "0": true)

/// Whether `text` is base64 data (xs:base64Binary).
///
/// -> bool
#let valid-base64(text) = {
  import "rare.typ": valid-base64
  valid-base64(text)
}

// Days per month of a format 102 date; 29 February is checked separately.
#let _days = (31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)

// Whether `text` is eight digits (a decimal without sign or point).
#let _digits8(text) = (
  text.len() == 8
    and _decimal in text
    and not ("." in text or "+" in text or "-" in text)
)

/// Whether `text` is a calendar date in the format 102 (YYYYMMDD).
///
/// -> bool
#let valid-date-102(text) = {
  if type(text) != str or not _digits8(text) { return false }
  let year = int(text.slice(0, 4))
  let month = int(text.slice(4, 6))
  let day = int(text.slice(6, 8))
  if month < 1 or month > 12 or day < 1 or day > _days.at(month - 1) {
    return false
  }
  let leap = (
    calc.rem(year, 4) == 0
      and (calc.rem(year, 100) != 0 or calc.rem(year, 400) == 0)
  )
  month != 2 or day <= 28 or leap
}

/// The root element of every profile and the namespaces of its prefixes.
#let root-tag = "rsm:CrossIndustryInvoice"
#let namespaces = (
  "xmlns:rsm": "urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100",
  "xmlns:qdt": "urn:un:unece:uncefact:data:standard:QualifiedDataType:100",
  "xmlns:ram": "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100",
  "xmlns:udt": "urn:un:unece:uncefact:data:standard:UnqualifiedDataType:100",
)

// The namespace declarations the root may have: its prefixes and the XML
// Schema instance namespace.
#let _declarations = (
  namespaces + ("xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance")
)

/// The kinds of findings after which the XML may not be well-formed, so
/// that Typst's XML parser (G4) must not read it: an invalid name, a
/// missing namespace declaration, or not exactly one root element.
#let malformed-kinds = ("name", "namespace", "root")

// The tables of the profiles, by profile: JSON files, read natively and only
// for the profile an invoice uses.
#let _profiles = (
  minimum: "minimum.json",
  basic-wl: "basic-wl.json",
  basic: "basic.json",
  en16931: "en16931.json",
  xrechnung: "xrechnung.json",
)

// The tables of a profile (see the top of this file), or none.
#let _tables(profile) = {
  let file = _profiles.at(profile, default: none)
  if file != none { json(file) }
}

// A problem the guard found: its kind, the official rule (or `none`, for
// which report.typ names the guard's own rule of the kind), the path of
// elements from the element that found it, and details.
#let _finding(kind, rule, path, ..details) = (
  (kind: kind, rule: rule, path: path) + details.named()
)

// The rule of the minimum (0) or the maximum (1) of a child: `rules` are
// as many as there are, or none.
#let _rule(rules, i) = if rules != none { rules.at(i, default: none) }

// Findings of the child `step` of the element `tag`: their paths from `tag`.
#let _lift(found, tag, step) = {
  let out = ()
  for f in found { out.push(f + (path: (tag, step) + f.path.slice(1))) }
  out
}

// The text of a written value.
#let _text(value) = if type(value) == str { value } else { plain-text(value) }

// An element without checks, for elements of no known position: the same
// output the checked writer produces (see rare.typ).
#let _raw(tag, body) = {
  import "rare.typ": raw
  raw(tag, body)
}

// The number of decimals of a decimal: as written (`lexical`, the
// Schematron's `string-length(substring-after(., '.'))`), or of its value
// (trailing zeros do not count).
#let _decimals(text, lexical) = {
  let parts = text.split(".")
  if parts.len() < 2 { return 0 }
  let fraction = parts.at(1)
  if not lexical { fraction = fraction.trim("0", at: end, repeat: true) }
  fraction.len()
}

// `none` when `value` is in the code list `spec` = [name, rule, exceptions,
// upper case], else the rule to report. A list is a string of its codes,
// each between two spaces (see lists.typ).
#let _code-rule(value, spec) = {
  let (name, rule, exceptions, casefold) = spec
  let code = if casefold { upper(value) } else { value }
  if (
    code != ""
      and not code.contains(" ")
      and (" " + code + " ") in code-lists.at(name)
  ) { return none }
  if exceptions != none { exceptions.at(value, default: rule) } else { rule }
}

// Checks the text of a leaf against its node [kind, attributes, list,
// prefix, decimals, date]; `attrs` are the attributes written.
#let _check-text(tag, text, node, attrs) = {
  let found = ()
  let (kind, _, list, prefix, fraction, date) = node
  if kind == "d" {
    if _decimal not in text {
      found.push(_finding(
        "lexical",
        none,
        (tag,),
        value: text,
        expected: "a decimal",
      ))
    }
    if fraction != none {
      let (limit, lexical, rule) = fraction
      if _decimals(text, lexical) > limit {
        found.push(_finding(
          "fraction",
          rule,
          (tag,),
          value: text,
          limit: limit,
        ))
      }
    }
  } else if kind == "b" and text not in _booleans {
    found.push(_finding(
      "lexical",
      none,
      (tag,),
      value: text,
      expected: "an indicator",
    ))
  } else if kind == "x" and not valid-base64(text) {
    found.push(_finding(
      "lexical",
      none,
      (tag,),
      value: text,
      expected: "base64 data",
    ))
  }
  if date != none and attrs.at("format", default: none) == "102" {
    if not valid-date-102(text) {
      // Eight digits that are no calendar date pass the official check
      // (CII-DT-097), but name no day: the guard's own rule.
      let rule = if _digits8(text) { "IP-GUARD-08" } else { date }
      found.push(_finding("date", rule, (tag,), value: text))
    }
  }
  if list != none {
    let rule = _code-rule(text, list)
    if rule != none {
      found.push(_finding("code", rule, (tag,), value: text, list: list.at(0)))
    }
  }
  if prefix != none {
    let (spec, when) = prefix
    if when == none or attrs.at(when.at(0), default: none) == when.at(1) {
      let characters = text.codepoints()
      let first = if characters == () { "" } else {
        characters.slice(0, calc.min(2, characters.len())).join()
      }
      let rule = _code-rule(first, spec)
      if rule != none {
        found.push(_finding(
          "prefix",
          rule,
          (tag,),
          value: first,
          list: spec.at(0),
        ))
      }
    }
  }
  found
}

// Checks the attributes of a leaf against its node: `attrs` are the
// attributes written, with their texts.
#let _check-attributes(tag, node, attrs) = {
  let found = ()
  let specs = node.at(1)
  for (name, value) in attrs {
    let spec = if specs == none { none } else { specs.at(name, default: none) }
    if spec == none {
      found.push(_finding("attribute", none, (tag,), name: name))
      import "rare.typ": attribute-name
      found += attribute-name(tag, name)
      continue
    }
    let (_, forbidden, list) = spec
    if forbidden != none {
      found.push(_finding("attribute-not-used", forbidden, (tag,), name: name))
    }
    if list != none {
      let rule = _code-rule(value, list)
      if rule != none {
        found.push(_finding(
          "code",
          rule,
          (tag,),
          value: value,
          name: name,
          list: list.at(0),
        ))
      }
    }
  }
  if specs != none {
    for (name, spec) in specs {
      let required = spec.at(0)
      if required != false and name not in attrs {
        let rule = if required == true { none } else { required }
        found.push(_finding("attribute-missing", rule, (tag,), name: name))
      }
    }
  }
  found
}

// A leaf: the element `tag` with its text and attributes, checked against
// its node (a kind or an array); `empty` is the rule of the profile that
// forbids an empty leaf, or none. Returns (XML, findings).
#let _leaf(tag, body, node, empty) = {
  if type(node) == str { node = (node, none, none, none, none, none) }
  if type(body) != dictionary {
    let text = if type(body) == str { body } else { plain-text(body) }
    let escaped = if _plain in text { text } else { xml-escape(text) }
    if escaped.trim() == "" { return ("", ()) }
    let found = _check-text(tag, text, node, (:))
    if node.at(1) != none { found += _check-attributes(tag, node, (:)) }
    return ("<" + tag + ">" + escaped + "</" + tag + ">", found)
  }
  // Attributes and text, written as `_raw` writes them.
  let attrs = (:)
  let written = ""
  let children = ""
  let text = none
  let found = ()
  for (key, value) in body {
    if key == "" {
      if type(value) == dictionary {
        import "rare.typ": unknown-in-leaf
        for (k, v) in value {
          let (r, f) = unknown-in-leaf(tag, k, v)
          children += r
          found += f
        }
      } else if value != none {
        text = if type(value) == str { value } else { plain-text(value) }
        children += if _plain in text { text } else { xml-escape(text) }
      }
    } else if key.starts-with("@") {
      if value != none {
        let name = key.slice(1)
        let v = if type(value) == str { value } else { plain-text(value) }
        written += (
          " "
            + name
            + "=\""
            + if _plain in v { v } else { xml-escape(v) }
            + "\""
        )
        attrs.insert(name, v)
      }
    } else {
      import "rare.typ": unknown-in-leaf
      let (r, f) = unknown-in-leaf(tag, key, value)
      children += r
      found += f
    }
  }
  if "" in body and children.trim() == "" { return ("", ()) }
  found += _check-attributes(tag, node, attrs)
  if children == "" {
    // An element without text: its text is checked as empty (no decimal,
    // no code), and a rule of the profile may forbid empty elements.
    if empty != none { found.push(_finding("empty", empty, (tag,))) }
    found += _check-text(tag, "", node, attrs)
    return ("<" + tag + written + " />", found)
  }
  if text != none { found += _check-text(tag, text, node, attrs) }
  ("<" + tag + written + ">" + children + "</" + tag + ">", found)
}

// The value of a discriminator path, e.g. ["ram:ID", "@schemeID"], in the
// tree of an element: a string, or `none`.
#let _discriminator(body, path) = {
  let value = body
  for step in path {
    if type(value) != dictionary { return none }
    value = value.at(step, default: none)
  }
  if type(value) == dictionary { value = value.at("", default: none) }
  if value == none or type(value) == array or type(value) == dictionary {
    return none
  }
  _text(value)
}

// Whether a subtree is written (the serializer leaves out `none`, blank text
// and elements with a blank value).
#let _present(value) = {
  if value == none { return false }
  if type(value) == array {
    for item in value { if _present(item) { return true } }
    return false
  }
  if type(value) == dictionary {
    if "" not in value { return true }
    let text = value.at("")
    if type(text) == dictionary {
      for item in text.values() { if _present(item) { return true } }
      return false
    }
    return text != none and xml-escape(text).trim() != ""
  }
  xml-escape(value).trim() != ""
}

// The written elements at a path of child elements below a tree.
#let _values(body, path) = {
  let level = (body,)
  for step in path {
    let next = ()
    for item in level {
      if type(item) != dictionary { continue }
      let value = item.at(step, default: none)
      if type(value) == array {
        for v in value { if _present(v) { next.push(v) } }
      } else if _present(value) { next.push(value) }
    }
    level = next
  }
  level
}

// The text of a leaf as written (see `_leaf`), or none when it is not
// written.
#let _leaf-text(value) = {
  if not _present(value) { return none }
  _text(if type(value) == dictionary { value.at("", default: none) } else {
    value
  })
}

// The check of a decimal against the value a rule of a VAT category wants:
// 1 above 0, 0 zero (as XPath compares them: an absent element is neither).
// A text that is no decimal passes here; its lexical check reports it.
#let _compares(value, expected) = {
  let text = _leaf-text(value)
  if text == none { return false }
  if _decimal not in text { return true }
  let zero = _zero in text
  if expected == 0 { zero } else { not zero and not text.starts-with("-") }
}

// The rules of the VAT category of a tax element (`body`, the child `step`
// of `tag`): the `checks` of its `category` (see lists.typ) on its rate
// ("r": above 0, 0, none, or "any" rate), its VAT amount ("a") and its
// exemption reason ("e").
#let _category-checks(tag, step, body, category, checks) = {
  let found = ()
  for (check, expected, rule) in checks {
    let (element, ok) = if check == "e" {
      let stated = (
        _present(body.at("ram:ExemptionReason", default: none))
          or _present(body.at("ram:ExemptionReasonCode", default: none))
      )
      ("ram:ExemptionReason", stated == expected)
    } else {
      let element = if check == "r" { "ram:RateApplicablePercent" } else {
        "ram:CalculatedAmount"
      }
      let value = body.at(element, default: none)
      (
        element,
        if expected == none { not _present(value) } else if expected == "any" {
          _present(value)
        } else { _compares(value, expected) },
      )
    }
    if not ok {
      found.push(_finding(
        "category",
        rule,
        (tag, step, element),
        category: category,
        check: check,
        expected: expected,
        value: _leaf-text(body.at(element, default: none)),
      ))
    }
  }
  found
}

// The rules of the VAT categories of the tax elements `value` (one, or an
// array) of the child `child` of `tag`, each by the category code it
// states: `rules` names their table in lists.typ (`t` of a node). One
// memoized call on small arguments, so that the lines of one tax are
// checked once.
#let _vat-checks(tag, child, value, rules) = {
  let table = vat-rules.at(rules)
  let many = type(value) == array
  let found = ()
  let i = 0
  for item in if many { value } else { (value,) } {
    i += 1
    if type(item) != dictionary { continue }
    let code = _discriminator(item, ("ram:CategoryCode",))
    let checks = if code == none { none } else {
      table.at(code, default: none)
    }
    if checks == none { continue }
    let step = if many { child + "[" + str(i) + "]" } else { child }
    found += _category-checks(tag, step, item, code, checks)
  }
  found
}

// The further checks of a complex node (`z`) on the values of its tree:
// `v`, `g` and `r` (`write` does the others as it writes the children).
#let _further-checks(tag, body, z, variants) = {
  let found = ()
  for (key, value, low, rule) in z.at("v", default: ()) {
    if variants.at(key, default: (:)).at(value, default: 0) < low {
      found.push(_finding("variant-min", rule, (tag, key), variant: value))
    }
  }
  for (path, low, high, rule) in z.at("g", default: ()) {
    let count = _values(body, path).len()
    if count < low or (high != none and count > high) {
      found.push(_finding(
        "aggregate",
        rule,
        (tag,),
        steps: path,
        count: count,
        low: low,
        high: high,
      ))
    }
  }
  for (kind, refs, rule) in z.at("r", default: ()) {
    // The VAT total (BT-110, BT-111) by the currency it is stated in: one
    // in each currency the settlement names, and no other.
    let currencies = ()
    for ref in refs {
      let value = body.at(ref, default: none)
      if value != none { currencies.push(_text(value)) }
    }
    let totals = ()
    for total in _values(body, (
      "ram:SpecifiedTradeSettlementHeaderMonetarySummation",
      "ram:TaxTotalAmount",
    )) {
      let currency = if type(total) == dictionary {
        total.at("@currencyID", default: none)
      }
      totals.push(if currency == none { none } else { _text(currency) })
    }
    if kind == "count" {
      for currency in currencies {
        let n = 0
        for c in totals { if c == currency { n += 1 } }
        if n > 1 {
          found.push(_finding(
            "xref-count",
            rule,
            (tag,),
            value: currency,
            count: n,
          ))
        }
      }
    } else {
      for currency in totals {
        if currency not in currencies {
          found.push(_finding("xref-other", rule, (tag,), value: currency))
        }
      }
    }
  }
  found
}

/// Serializes the builder's element tree `data` and checks it against the
/// guard tables of `profile` in the same pass (see `dict-to-xml`).
///
/// -> dictionary
#let write(data, profile) = {
  let tables = _tables(profile)
  if tables == none {
    panic("no guard tables for the profile " + repr(profile))
  }
  let nodes = tables.nodes
  let empty = tables.empty
  if data == none { data = (:) }
  if type(data) != dictionary {
    // No element tree: its text, and no root element.
    return (
      xml: xml-escape(data),
      findings: (_finding("root", none, (root-tag,), missing: true),),
    )
  }

  // An element of a complex node. Returns (XML, findings). The checks of
  // G1 on the names of the children run as they are written: that each is
  // in schema order after the one before and within its maximum, and after
  // the loop that the required ones are there and the node's further checks
  // on names (`e`, `y`, `x`). Their findings follow those of the children.
  let element(tag, body, id) = {
    let node = nodes.at(id)
    let children = node.c
    let out = ""
    let attrs = ""
    let found = ()
    let problems = ()
    // The index of the last child written, the number of children written
    // and of those among them the node requires.
    let last = -1
    let written = 0
    let required = 0
    // The children the node allows that are not written.
    let skipped = ()
    let variants = (:)
    for (key, value) in body {
      if key not in children {
        if value == none { continue }
        // The namespace declarations of the root, its only attributes.
        if id == 0 and key.starts-with("@") and key.slice(1) in _declarations {
          attrs += " " + key.slice(1) + "=\"" + xml-escape(value) + "\""
          continue
        }
        // Another attribute, text, or an element the profile does not use
        // here or does not know.
        import "rare.typ": other-child
        let (a, x, f) = other-child(
          tag,
          key,
          value,
          node.at("u", default: (:)).at(key, default: none),
          if id == 0 { _declarations },
        )
        attrs += a
        out += x
        found += f
        continue
      }
      let (action, index, low, high, target, rules) = children.at(key)
      let t = type(value)
      let count = 1
      // A leaf that a plain text of its form satisfies: a text, a decimal,
      // an indicator, or a code of its list (a code has no space and nothing
      // to escape).
      if (
        t == str
          and (
            action == "s" and _plain in value
              or action == "d2" and _decimal2 in value
              or action == "d" and _decimal in value
              or action == "b" and value in _booleans
              or (
                type(action) == str
                  and action.len() > 2
                  and not (" " in value)
                  and (" " + value + " ") in code-lists.at(action)
              )
          )
      ) {
        out += "<" + key + ">" + value + "</" + key + ">"
      } else if t == dictionary and type(action) == int {
        let (xml, f) = element(key, value, action)
        if f != () { found += _lift(f, tag, key) }
        if xml == "" {
          skipped.push(key)
          continue
        }
        out += xml
      } else if value == none {
        skipped.push(key)
        continue
      } else {
        // Everything else: repeated elements, variants, leaves with further
        // checks or attributes, other values.
        let n = nodes.at(target)
        let many = t == array
        let dispatch = type(n) == dictionary and "d" in n
        count = 0
        // Leaves written without text: a required one counts as missing,
        // as the official rules require its text (`normalize-space(..) !=
        // ''`, XRechnung's `[boolean(normalize-space(.))]`).
        let blank = 0
        let i = 0
        for item in if many { value } else { (value,) } {
          i += 1
          if item == none { continue }
          let child = target
          if dispatch {
            // The node of the variant, by the value of the discriminator.
            let v = _discriminator(item, n.d)
            let variant = if v != none and v in n.m { v } else { "*" }
            child = if variant == "*" { n.o } else { n.m.at(variant) }
            let seen = variants.at(key, default: (:))
            seen.insert(variant, seen.at(variant, default: 0) + 1)
            variants.insert(key, seen)
          }
          let (xml, f) = if type(child) == str {
            // A variant the profile does not use.
            import "rare.typ": unchecked
            unchecked(key, item, child)
          } else if type(nodes.at(child)) != dictionary {
            let (xml, f) = _leaf(key, item, nodes.at(child), empty)
            // A leaf without text is written as an empty element.
            if xml.ends-with(" />") { blank += 1 }
            (xml, f)
          } else if type(item) == dictionary {
            element(key, item, child)
          } else {
            // Text where the schema expects elements.
            import "rare.typ": unchecked
            unchecked(key, item, none)
          }
          if f != () {
            found += _lift(f, tag, if many { key + "[" + str(i) + "]" } else {
              key
            })
          }
          if xml == "" { continue }
          out += xml
          count += 1
        }
        if blank > 0 and blank == count and low > 0 {
          found.push(_finding("blank", _rule(rules, 0), (tag, key)))
        }
        if dispatch and "k" in n {
          for (v, limit) in n.k {
            let c = variants.at(key, default: (:)).at(v, default: 0)
            if c > limit.at(0) {
              found.push(_finding(
                "variant-max",
                limit.at(1),
                (tag, key),
                variant: v,
                count: c,
                limit: limit.at(0),
              ))
            }
          }
        }
        if count == 0 {
          skipped.push(key)
          continue
        }
      }
      // The child is written `count` times: its order, number and whether
      // the node requires it.
      written += 1
      if index < last { problems.push(_finding("order", none, (tag, key))) }
      last = index
      if low > 0 { required += 1 }
      if count > 1 and high != none and count > high {
        problems.push(_finding(
          "max",
          _rule(rules, 1),
          (tag, key),
          count: count,
          limit: high,
        ))
      }
    }
    // A child the node allows is written when it is in the tree and not
    // skipped.
    if required < node.n {
      for (key, spec) in children {
        if spec.at(2) > 0 and (key not in body or key in skipped) {
          problems.push(_finding("min", _rule(spec.at(5), 0), (tag, key)))
        }
      }
    }
    let z = if "z" in node { node.z }
    if z != none {
      if "y" in z {
        for (tags, rule) in z.y {
          let any = false
          for key in tags {
            if key in body and key not in skipped { any = true }
          }
          if not any {
            problems.push(_finding("any-of", rule, (tag,), tags: tags))
          }
        }
      }
      if "x" in z {
        for (tags, rule) in z.x {
          let all = true
          for key in tags {
            if key not in body or key in skipped { all = false }
          }
          if all {
            problems.push(_finding("exclusive", rule, (tag,), tags: tags))
          }
        }
      }
      if "e" in z and written == 0 {
        problems.push(_finding("empty", z.e, (tag,)))
      }
    }
    if problems != () { found += problems }
    if z != none {
      if "t" in z {
        // The tax elements among the children, by their VAT categories.
        for (child, rules) in z.t {
          let value = body.at(child, default: none)
          if value != none {
            let f = _vat-checks(tag, child, value, rules)
            if f != () { found += f }
          }
        }
      }
      if "v" in z or "g" in z or "r" in z {
        found += _further-checks(tag, body, z, variants)
      }
    }
    if "" in body and out.trim() == "" { return ("", found) }
    (
      if out == "" { "<" + tag + attrs + " />" } else {
        "<" + tag + attrs + ">" + out + "</" + tag + ">"
      },
      found,
    )
  }

  let xml = ""
  let findings = ()
  for (tag, body) in data {
    if body == none { continue }
    if tag != root-tag or type(body) != dictionary {
      // A second root, or text: the XML is no document of the schema.
      import "rare.typ": not-root
      let (r, f) = not-root(tag, body)
      xml += r
      findings += f
      continue
    }
    for (name, uri) in namespaces {
      if body.at("@" + name, default: none) != uri {
        findings.push(_finding(
          "namespace",
          none,
          (tag,),
          name: name,
          value: uri,
        ))
      }
    }
    let (x, f) = element(tag, body, 0)
    xml += x
    findings += f
  }
  if xml.trim() == "" or data.at(root-tag, default: none) == none {
    findings.push(_finding("root", none, (root-tag,), missing: true))
  }
  (xml: xml, findings: findings)
}
