// The write guard (G1 and G2): the serializer of the e-invoice XML, which
// checks every element against the guard tables of its profile while it
// writes it. `dict-to-xml` (../xml.typ) calls it; the tables of a profile
// load when the first invoice of the profile is written.
//
// The builder (build.typ) describes the document as a tree of dictionaries:
// keys are element names, `@name` keys attributes and the key `""` the text
// of an element with attributes; an array repeats its element, and `none`
// or a blank text leaves the element out. `write` writes this tree and, in
// the same pass, checks every element against the node of its position in
// the guard tables of the profile (<profile>.json next to this file,
// generated by tools/zugferd/gen_guard.py from the official XSD and
// Schematron artefacts):
//
// - G1, structure: the profile's schema knows the element at its position
//   and does not mark it as not used there; it is in schema order and
//   number (maxOccurs and the Schematron's counts); every required element
//   is there with its text (a leaf without text counts as missing), and
//   only the attributes the schema allows.
// - G2, values: the lexical form of decimals, indicators and format 102
//   dates (calendar dates), the maximum number of decimals (BR-DEC-*),
//   every code in the official code lists of its position, and on a tax
//   element what its VAT category requires of its rate, VAT amount and
//   exemption reason (e.g. BR-S-05, BR-E-10).
//
// The XML does not depend on the checks: the serializer writes the same
// document whatever it finds and returns what it found as findings, which
// process-zugferd turns into diagnostics (report.typ).
//
// Two writers share this work. `write` below writes a document in one pass
// as long as every check passes: a subtree in which a check fails, or with
// anything a valid invoice does not have (an element the tables do not
// know, text to convert, an attribute to escape, ...), is `none`, and the
// document then goes to the checked writer of rare.typ. That one is the
// reference: it writes the same XML and reports every finding with its rule
// and the path of the element (report.typ). So a valid invoice never loads
// it. The tests of the guard (tests/zugferd/guard) and the mutation test
// (tools/zugferd/mutate.py) compare both writers on every tree they write.
//
// The tables (JSON: `nodes`, and `empty`, the rule that forbids an empty
// leaf, or null). A node is an element at a position; a child names its
// node by index. A leaf node is its kind ("s" text, "d" decimal, "b"
// indicator, "x" binary) or an array [kind, attributes, code list, prefix
// list, decimals, date]: attributes map a name to [required, the rule that
// marks it as not used here, code list]; a code list is [name in lists.typ,
// rule, the codes other validators reject: their rule, compared in upper
// case]; a prefix list is [code list, [attribute, value] it applies to];
// decimals are [maximum, counted as written, rule], and date is the rule of
// a format 102 date. A complex node is an object {n: number of required
// children, z: further checks, u: the children the profile does not use
// here, each with the rule that says so, c: the children} (z and u only
// when there are any). A child maps its name to [action, index in the
// schema's sequence, minimum (0 or 1), maximum or null, node, rules]: the
// rules of the minimum and the maximum, as far as there are any, or null.
// The action is the writer's fast path: the index of a complex node, which a
// dictionary value is written as; the class of plain texts that pass every
// check of the leaf by their form alone ("s" any text, "d" a decimal, "d2" a
// decimal with at most two decimals, "b" an indicator); the name of the code
// list (of lists.typ) of a leaf whose only check it is; or null. An element the
// Schematron treats by the value of a discriminator (e.g. `ram:ID/@schemeID`
// of a tax registration) has a dispatch as its node: {d: discriminator path,
// m: value -> node or the rule that forbids it, o: node or rule of any other
// value, k: value -> [maximum, rule]}. Further checks: `e` the rule that
// forbids an empty element, `v` minimum numbers of variants, `g` counts over
// paths, `y` children of which one is required, `x` children that exclude
// each other, `r` the currency cross references of the VAT total, `t` the
// tax elements among the children, each with the name of the table of the
// rules of the VAT categories where it is (`vat-rules` of lists.typ): per
// category code, (check, value, rule) of the rate, the VAT amount and the
// exemption reason.
//
// Performance (concept 6.4, budget 0.5 ms per invoice line): Typst memoizes
// every call of a closure, hashing its arguments, and spends about a
// microsecond on a call of a function or method, a fraction of that on an
// operator or a field access. So the writer makes one call per complex
// element and writes the common children (a plain text, a decimal, a code)
// in its loop, tested with operators; it checks the order and number of the
// children in the same loop, as it writes them. A leaf with further checks
// goes through `_leaf`, memoized, so a leaf that repeats is checked once.

#import "../xml.typ": escaped-class, xml-escape
#import "lists.typ": lists as code-lists, vat-rules

// A text written as it is: not blank, and nothing `xml-escape` changes.
#let _plain = {
  let c = escaped-class
  regex("^[^" + c + "]*[^\\s" + c + "][^" + c + "]*$")
}
// Lexical space of xs:decimal without the whitespace the XSD collapses
// (the serializer never writes any): digits, at most one point, a sign.
#let _decimal = regex("^[+-]?(?:[0-9]+(?:\\.[0-9]*)?|\\.[0-9]+)$")
// The same with at most two decimals as written (fast class "d2").
#let _decimal2 = regex("^[+-]?(?:[0-9]+(?:\\.[0-9]{0,2})?|\\.[0-9]{1,2})$")
#let _booleans = ("true": true, "false": true, "1": true, "0": true)

/// Whether `text` is base64 data (xs:base64Binary).
///
/// -> bool
#let valid-base64(text) = {
  import "rare.typ": valid-base64
  valid-base64(text)
}

// Days per month of a format 102 date; 29 February is checked separately.
#let _days = (31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)

// Whether `text` is eight digits (a decimal without sign or point).
#let _digits8(text) = (
  text.len() == 8
    and _decimal in text
    and not ("." in text or "+" in text or "-" in text)
)

/// Whether `text` is a calendar date in the format 102 (YYYYMMDD).
///
/// -> bool
#let valid-date-102(text) = {
  if type(text) != str or not _digits8(text) { return false }
  let year = int(text.slice(0, 4))
  let month = int(text.slice(4, 6))
  let day = int(text.slice(6, 8))
  if month < 1 or month > 12 or day < 1 or day > _days.at(month - 1) {
    return false
  }
  let leap = (
    calc.rem(year, 4) == 0
      and (calc.rem(year, 100) != 0 or calc.rem(year, 400) == 0)
  )
  month != 2 or day <= 28 or leap
}

/// The root element of every profile and the namespaces of its prefixes.
#let root-tag = "rsm:CrossIndustryInvoice"
#let namespaces = (
  "xmlns:rsm": "urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100",
  "xmlns:qdt": "urn:un:unece:uncefact:data:standard:QualifiedDataType:100",
  "xmlns:ram": "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100",
  "xmlns:udt": "urn:un:unece:uncefact:data:standard:UnqualifiedDataType:100",
)

// The namespace declarations the root may have: its prefixes and the XML
// Schema instance namespace.
#let _declarations = (
  namespaces + ("xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance")
)

/// The kinds of findings after which the XML may not be well-formed, so
/// that Typst's XML parser (G4) must not read it: an invalid name, a
/// missing namespace declaration, or not exactly one root element.
#let malformed-kinds = ("name", "namespace", "root")

// The tables of the profiles, by profile: JSON files, read natively and only
// for the profile an invoice uses.
#let _profiles = (
  minimum: "minimum.json",
  basic-wl: "basic-wl.json",
  basic: "basic.json",
  en16931: "en16931.json",
  xrechnung: "xrechnung.json",
)

// The tables of a profile (see the top of this file), or none.
#let _tables(profile) = {
  let file = _profiles.at(profile, default: none)
  if file != none { json(file) }
}

// The text of a written value.
#let _text(value) = if type(value) == str { value } else {
  import "../../utils/text.typ": plain-text
  plain-text(value)
}

// An element without checks, for elements of no known position: the same
// output the checked writer produces (see rare.typ).
#let _raw(tag, body) = {
  import "rare.typ": raw
  raw(tag, body)
}

// The number of decimals of a decimal: as written (`lexical`, the
// Schematron's `string-length(substring-after(., '.'))`), or of its value
// (trailing zeros do not count).
#let _decimals(text, lexical) = {
  let parts = text.split(".")
  if parts.len() < 2 { return 0 }
  let fraction = parts.at(1)
  if not lexical { fraction = fraction.trim("0", at: end, repeat: true) }
  fraction.len()
}

// `none` when `value` is in the code list `spec` = [name, rule, exceptions,
// upper case], else the rule to report. A list is a string of its codes,
// each between two spaces (see lists.typ).
#let _code-rule(value, spec) = {
  let (name, rule, exceptions, casefold) = spec
  let code = if casefold { upper(value) } else { value }
  if (
    code != ""
      and not code.contains(" ")
      and (" " + code + " ") in code-lists.at(name)
  ) { return none }
  if exceptions != none { exceptions.at(value, default: rule) } else { rule }
}

// The value of a discriminator path, e.g. ["ram:ID", "@schemeID"], in the
// tree of an element: a string, or `none`.
#let _discriminator(body, path) = {
  let value = body
  for step in path {
    if type(value) != dictionary { return none }
    value = value.at(step, default: none)
  }
  if type(value) == dictionary { value = value.at("", default: none) }
  if value == none or type(value) == array or type(value) == dictionary {
    return none
  }
  _text(value)
}

// Whether a text is written: not blank once escaped.
#let _written(text) = (
  type(text) == str and _plain in text or xml-escape(text).trim() != ""
)

// Whether a subtree is written (the serializer leaves out `none`, blank text
// and elements with a blank value).
#let _present(value) = {
  if value == none { return false }
  if type(value) == array {
    for item in value { if _present(item) { return true } }
    return false
  }
  if type(value) == dictionary {
    if "" not in value { return true }
    let text = value.at("")
    if type(text) == dictionary {
      for item in text.values() { if _present(item) { return true } }
      return false
    }
    return text != none and _written(text)
  }
  _written(value)
}

// The written elements at a path of child elements below a tree.
#let _values(body, path) = {
  let level = (body,)
  for step in path {
    let next = ()
    for item in level {
      if type(item) != dictionary { continue }
      let value = item.at(step, default: none)
      if type(value) == array {
        for v in value { if _present(v) { next.push(v) } }
      } else if _present(value) { next.push(value) }
    }
    level = next
  }
  level
}

// The text of a leaf as written (see `_leaf`), or none when it is not
// written.
#let _leaf-text(value) = {
  if not _present(value) { return none }
  _text(if type(value) == dictionary { value.at("", default: none) } else {
    value
  })
}

// The check of a decimal against the value a rule of a VAT category wants:
// 1 above 0, 0 zero (as XPath compares them: an absent element is neither).
// A text that is no decimal passes here; its lexical check reports it. A
// decimal is zero when its digits are: without them, its sign and its point
// nothing is left (a replacement is cheaper than a pattern that only a few
// checks per invoice need).
#let _compares(value, expected) = {
  let text = _leaf-text(value)
  if text == none { return false }
  if _decimal not in text { return true }
  let zero = (
    text.replace("0", "").replace(".", "").replace("+", "").replace("-", "")
      == ""
  )
  if expected == 0 { zero } else { not zero and not text.starts-with("-") }
}

// Whether a tax element (`body`) passes the check `check` of its VAT
// category with the value `expected` (see lists.typ): its exemption reason
// ("e": stated or not), its rate ("r") or its VAT amount ("a": none absent,
// "any" there, 0 zero, 1 above 0).
#let _category-ok(body, check, expected) = {
  if check == "e" {
    let stated = (
      _present(body.at("ram:ExemptionReason", default: none))
        or _present(body.at("ram:ExemptionReasonCode", default: none))
    )
    return stated == expected
  }
  let value = body.at(
    if check == "r" { "ram:RateApplicablePercent" } else {
      "ram:CalculatedAmount"
    },
    default: none,
  )
  if expected == none { not _present(value) } else if expected == "any" {
    _present(value)
  } else { _compares(value, expected) }
}

// The currencies of the currency cross references of a settlement (`refs`,
// e.g. the invoice currency) and those of its VAT totals (`none` for a VAT
// total without a currency), as written.
#let _xref-values(body, refs) = {
  let currencies = ()
  for ref in refs {
    let value = body.at(ref, default: none)
    if value != none { currencies.push(_text(value)) }
  }
  let totals = ()
  for total in _values(body, (
    "ram:SpecifiedTradeSettlementHeaderMonetarySummation",
    "ram:TaxTotalAmount",
  )) {
    let currency = if type(total) == dictionary {
      total.at("@currencyID", default: none)
    }
    totals.push(if currency == none { none } else { _text(currency) })
  }
  (currencies, totals)
}

// A leaf: the element `tag` with its text and attributes, if its node (a
// kind or an array, see `_leaf` of rare.typ) finds nothing in it. `""` when
// it is left out, `none` when it has to go to the checked writer: anything
// it would report, and what the builder does not write (text that is no
// string, an element below a leaf, an attribute to escape, a leaf without
// text, base64 data).
#let _leaf(tag, body, node) = {
  let (kind, specs, list, prefix, fraction, date) = if type(node) == str {
    (node, none, none, none, none, none)
  } else { node }
  let text = body
  let written = ""
  let attrs = (:)
  if type(body) == dictionary {
    text = none
    for (key, value) in body {
      if key == "" {
        text = value
      } else if key.starts-with("@") {
        if value == none { continue }
        if type(value) != str or _plain not in value { return none }
        let name = key.slice(1)
        written += " " + name + "=\"" + value + "\""
        attrs.insert(name, value)
      } else { return none }
    }
    if text == none { return if "" in body { "" } else { none } }
  }
  if type(text) != str { return none }
  let escaped = if _plain in text { text } else { xml-escape(text) }
  if escaped.trim() == "" { return "" }
  // The attributes: known here, used, of their lists, and every required
  // one written.
  for (name, value) in attrs {
    let spec = if specs != none { specs.at(name, default: none) }
    if spec == none { return none }
    let (_, forbidden, codes) = spec
    if forbidden != none or codes != none and _code-rule(value, codes) != none {
      return none
    }
  }
  if specs != none {
    for (name, spec) in specs {
      if spec.at(0) != false and name not in attrs { return none }
    }
  }
  // The text: its lexical form, decimals, date, code and prefix.
  if kind == "d" {
    if _decimal not in text { return none }
    if fraction != none and _decimals(text, fraction.at(1)) > fraction.at(0) {
      return none
    }
  } else if kind == "b" and text not in _booleans or kind == "x" {
    return none
  }
  if (
    date != none
      and attrs.at("format", default: none) == "102"
      and not valid-date-102(text)
  ) { return none }
  if list != none and _code-rule(text, list) != none { return none }
  if prefix != none {
    let (spec, when) = prefix
    if when == none or attrs.at(when.at(0), default: none) == when.at(1) {
      let characters = text.codepoints()
      let first = if characters == () { "" } else {
        characters.slice(0, calc.min(2, characters.len())).join()
      }
      if _code-rule(first, spec) != none { return none }
    }
  }
  "<" + tag + written + ">" + escaped + "</" + tag + ">"
}

// Whether the tax elements `value` (one, or an array) pass the rules of the
// VAT category each states: `rules` names their table in lists.typ (`t` of
// a node). One memoized call on small arguments, so that the lines of one
// tax are checked once.
#let _vat-ok(value, rules) = {
  let table = vat-rules.at(rules)
  for item in if type(value) == array { value } else { (value,) } {
    if type(item) != dictionary { continue }
    let code = _discriminator(item, ("ram:CategoryCode",))
    let checks = if code != none { table.at(code, default: none) }
    if checks == none { continue }
    for (check, expected, _) in checks {
      if not _category-ok(item, check, expected) { return false }
    }
  }
  true
}

// Whether the further checks `v`, `g` and `r` of a complex node (`z`) pass
// on the values of its tree (see `_further-checks` of rare.typ).
#let _further-ok(body, z, variants) = {
  for (key, value, low, _) in z.at("v", default: ()) {
    if variants.at(key, default: (:)).at(value, default: 0) < low {
      return false
    }
  }
  for (path, low, high, _) in z.at("g", default: ()) {
    let count = _values(body, path).len()
    if count < low or high != none and count > high { return false }
  }
  for (kind, refs, _) in z.at("r", default: ()) {
    let (currencies, totals) = _xref-values(body, refs)
    if kind == "count" {
      for currency in currencies {
        let n = 0
        for c in totals { if c == currency { n += 1 } }
        if n > 1 { return false }
      }
    } else {
      for currency in totals {
        if currency not in currencies { return false }
      }
    }
  }
  true
}

/// Serializes the builder's element tree `data` and checks it against the
/// guard tables of `profile` in the same pass (see `dict-to-xml`): a
/// document that passes every check here, any other with the checked
/// writer of rare.typ, which reports what it finds. With `fallback: false`,
/// a document that does not pass every check here is `none`, so that tests
/// can see that a valid invoice never needs the checked writer.
///
/// Returns `(xml: .., findings: ..)`.
///
/// -> dictionary | none
#let write(data, profile, fallback: true) = {
  let tables = _tables(profile)
  if tables == none {
    panic("no guard tables for the profile " + repr(profile))
  }
  let nodes = tables.nodes

  // An element of a complex node, as the checked writer writes it, or
  // `none` when a check fails in its tree (or it has something the builder
  // does not write). The checks of G1 on the names of the children run as
  // they are written: that each is known, in schema order after the one
  // before and within its maximum; after the loop, that the required ones
  // are written and the node's further checks.
  let element(tag, body, id) = {
    let node = nodes.at(id)
    let children = node.c
    let out = ""
    // The index of the last child written (-1: none yet) and the number of
    // children written that the node requires (a minimum is 0 or 1).
    let last = -1
    let required = 0
    // The children the node allows that are not written, and the variants
    // of each child with a discriminator.
    let skipped = ()
    let variants = (:)
    for (key, value) in body {
      let spec = children.at(key, default: none)
      if spec == none {
        // Nothing, or the namespace declarations of the root (see `write`);
        // text (`""`) goes to the checked writer even without a value.
        if (
          key != ""
            and (
              value == none
                or id == 0
                  and key.starts-with("@")
                  and key.slice(1) in _declarations
            )
        ) { continue }
        return none
      }
      if value == none {
        skipped.push(key)
        continue
      }
      let (action, index, low, high, target, _) = spec
      let t = type(value)
      // A leaf that a plain text of its form satisfies: a text, a decimal,
      // an indicator, or a code of its list (a code has no space and nothing
      // to escape).
      if (
        t == str
          and (
            action == "s" and _plain in value
              or action == "d2" and _decimal2 in value
              or action == "d" and _decimal in value
              or action == "b" and value in _booleans
              or (
                type(action) == str
                  and action.len() > 2
                  and not (" " in value)
                  and (" " + value + " ") in code-lists.at(action)
              )
          )
      ) {
        out += "<" + key + ">" + value + "</" + key + ">"
      } else if t == dictionary and type(action) == int {
        let xml = element(key, value, action)
        if xml == none { return none }
        if xml == "" {
          skipped.push(key)
          continue
        }
        out += xml
      } else {
        // Everything else: repeated elements, variants, leaves with further
        // checks or attributes, other values.
        let n = nodes.at(target)
        let dispatch = type(n) == dictionary and "d" in n
        let count = 0
        for item in if t == array { value } else { (value,) } {
          if item == none { continue }
          let child = target
          if dispatch {
            // The node of the variant, by the value of the discriminator;
            // a variant the profile does not use is a finding.
            let v = _discriminator(item, n.d)
            let variant = if v != none and v in n.m { v } else { "*" }
            child = if variant == "*" { n.o } else { n.m.at(variant) }
            if type(child) == str { return none }
            let seen = variants.at(key, default: (:))
            seen.insert(variant, seen.at(variant, default: 0) + 1)
            variants.insert(key, seen)
          }
          let xml = if type(nodes.at(child)) != dictionary {
            _leaf(key, item, nodes.at(child))
          } else if type(item) == dictionary { element(key, item, child) }
          // `none` also for text where the schema expects elements.
          if xml == none { return none }
          if xml != "" {
            out += xml
            count += 1
          }
        }
        if dispatch and "k" in n {
          for (v, limit) in n.k {
            if variants.at(key, default: (:)).at(v, default: 0) > limit.at(0) {
              return none
            }
          }
        }
        if count == 0 {
          skipped.push(key)
          continue
        }
        // Written `count` times: its order, its number, and whether the
        // node requires it.
        if index < last or count > 1 and high != none and count > high {
          return none
        }
        last = index
        required += low
        continue
      }
      // Written once: its order and whether the node requires it.
      if index < last { return none }
      last = index
      required += low
    }
    if required < node.n { return none }
    if "z" in node {
      let z = node.z
      for (tags, _) in z.at("y", default: ()) {
        let any = false
        for key in tags {
          if key in body and key not in skipped { any = true }
        }
        if not any { return none }
      }
      for (tags, _) in z.at("x", default: ()) {
        let all = true
        for key in tags {
          if key not in body or key in skipped { all = false }
        }
        if all { return none }
      }
      if "e" in z and last == -1 { return none }
      for (child, rules) in z.at("t", default: (:)) {
        let value = body.at(child, default: none)
        if value != none and not _vat-ok(value, rules) { return none }
      }
      if (
        ("v" in z or "g" in z or "r" in z)
          and not _further-ok(body, z, variants)
      ) { return none }
    }
    if out == "" { "<" + tag + " />" } else {
      "<" + tag + ">" + out + "</" + tag + ">"
    }
  }

  // The root element with its namespace declarations, or the checked
  // writer for anything else: no tree, a second root or text next to it, a
  // namespace declared wrongly, or a finding below.
  let body = if type(data) == dictionary and data.len() == 1 {
    data.at(root-tag, default: none)
  }
  let xml = none
  if type(body) == dictionary {
    let declared = true
    for (name, uri) in namespaces {
      if body.at("@" + name, default: none) != uri { declared = false }
    }
    if declared { xml = element(root-tag, body, 0) }
  }
  if xml == none {
    if not fallback { return none }
    import "rare.typ": write as checked
    return checked(data, profile)
  }
  let attrs = ""
  for (key, value) in body {
    if value != none and key.starts-with("@") {
      let v = if type(value) == str and _plain in value { value } else {
        xml-escape(value)
      }
      attrs += " " + key.slice(1) + "=\"" + v + "\""
    }
  }
  (xml: "<" + root-tag + attrs + xml.slice(root-tag.len() + 1), findings: ())
}
