"""Every business term of EN 16931 has a disposition in invoice-pro.

tools/zugferd/bt-disposition.toml says for every business term (BT-1 to
BT-165; BT-4 is not defined) and business group (BG-1 to BG-32) of the
semantic model of EN 16931-1 what invoice-pro does with it:

  input        an input of invoice-pro states it   (`input`: which one)
  derived      invoice-pro derives it              (`source`: from what)
  unsupported  invoice-pro does not state it       (`reason`: why)

The check fails when a term has no entry, an entry names no term of EN 16931,
or a disposition lacks its input, source or reason. So no business term is
left without a decision, and a value without an input of its own cannot end
up in another business term unnoticed (issue #42). scripts/zugferd-corpus
runs it before the corpus.

The tables of docs/docs/e-invoicing/invoice-data/business-terms.md are
generated from the table: the check also fails when they differ, and
--update-docs rewrites them.

Usage: bt_disposition.py [--update-docs] [--docs PATH] [TABLE]
"""

import argparse
import sys
import tomllib
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
TABLE = HERE / "bt-disposition.toml"
DOCS = HERE.parents[1] / "docs" / "docs" / "e-invoicing" / "invoice-data" / "business-terms.md"
# The generated part of the documentation sits between these two lines.
DOCS_BEGIN = '[//]: # "business-term tables: generated by tools/zugferd/bt_disposition.py --update-docs"'
DOCS_END = '[//]: # "end of the business-term tables"'

# The business terms and groups of EN 16931-1:2017.
TERMS = [f"BT-{n}" for n in range(1, 166) if n != 4] + [f"BG-{n}" for n in range(1, 33)]

# The key each disposition needs, next to `name`.
DISPOSITIONS = {"input": "input", "derived": "source", "unsupported": "reason"}
OPTIONAL = {"note"}

# The parts of the semantic model the documentation lists the terms by: its
# title, and the term that starts it in the table.
AREAS = (
    ("Invoice", "BT-1"),
    ("Seller", "BG-4"),
    ("Buyer", "BG-7"),
    ("Payee", "BG-10"),
    ("Seller Tax Representative", "BG-11"),
    ("Delivery and Invoicing Period", "BG-13"),
    ("Payment Instructions", "BG-16"),
    ("Document Level Allowances and Charges", "BG-20"),
    ("Totals and VAT Breakdown", "BG-22"),
    ("Additional Supporting Documents", "BG-24"),
    ("Invoice Lines", "BG-25"),
)
# How the documentation names the dispositions.
SHOWN = {"input": "input", "derived": "derived", "unsupported": "not supported"}


def load(path):
    """The parsed table (raises tomllib.TOMLDecodeError)."""
    return tomllib.loads(Path(path).read_text(encoding="utf-8"))


def check(table):
    """The problems of a parsed table, as messages; [] if it is complete."""
    terms = table.get("terms")
    if not isinstance(terms, dict):
        return ["the table has no [terms] table"]
    problems = [f"{term}: has no disposition" for term in TERMS if term not in terms]
    known = set(TERMS)
    for term, entry in terms.items():
        if term not in known:
            problems.append(f"{term}: is no business term of EN 16931 (BT-1 to BT-165 without BT-4, BG-1 to BG-32)")
            continue
        if not isinstance(entry, dict):
            problems.append(f"{term}: must be a table with `name` and `disposition`")
            continue
        if not str(entry.get("name", "")).strip():
            problems.append(f"{term}: has no `name`")
        disposition = entry.get("disposition")
        if disposition not in DISPOSITIONS:
            problems.append(f"{term}: disposition {disposition!r} is none of {', '.join(DISPOSITIONS)}")
            continue
        key = DISPOSITIONS[disposition]
        if not str(entry.get(key, "")).strip():
            problems.append(f"{term}: a disposition {disposition!r} needs `{key}`")
        unknown = sorted(set(entry) - {"name", "disposition", key} - OPTIONAL)
        if unknown:
            problems.append(f"{term}: unknown keys {', '.join(unknown)} (a {disposition!r} term has `{key}`)")
    return problems


def counts(table):
    """How many terms have each disposition."""
    return Counter(entry.get("disposition") for entry in table.get("terms", {}).values() if isinstance(entry, dict))


def _cell(text):
    """A text as the cell of a Markdown table."""
    if any(ch in text for ch in "<{}"):
        raise ValueError(f"{text!r}: the documentation is MDX, where <, {{ and }} are markup; rephrase it")
    return text.replace("|", "\\|")


def _details(entry):
    """The input, source or reason of an entry, with its note."""
    text = entry[DISPOSITIONS[entry["disposition"]]]
    return _cell(text + (f"; {entry['note']}" if entry.get("note") else ""))


def _table(rows, header):
    """A Markdown table in prettier's layout: every column as wide as its
    widest cell, left-aligned."""
    widths = [max(len(row[i]) for row in [header] + rows) for i in range(len(header))]
    lines = ["| " + " | ".join(cell.ljust(widths[i]) for i, cell in enumerate(header)) + " |"]
    lines.append("| " + " | ".join(":" + "-" * (widths[i] - 1) for i in range(len(header))) + " |")
    for row in rows:
        lines.append("| " + " | ".join(cell.ljust(widths[i]) for i, cell in enumerate(row)) + " |")
    return lines


def docs_block(table):
    """The generated part of the documentation of a complete table: the
    numbers, the terms invoice-pro does not support, and every term by the
    part of the semantic model it belongs to."""
    terms = table["terms"]
    order = list(terms)
    starts = [order.index(first) for _, first in AREAS]
    if starts != sorted(starts) or starts[0] != 0:
        raise ValueError(f"the terms that start the parts of AREAS are not in table order: {starts}")
    n = counts(table)
    out = [
        f"Of the {len(TERMS)} business terms and groups of EN 16931, `invoice-pro` states {n['input']} from an "
        f"input, derives {n['derived']} and does not support {n['unsupported']}.",
        "",
        "## Not Supported",
        "",
    ]
    rows = [[f"`{term}`", entry["name"], _details(entry)] for term, entry in terms.items() if entry["disposition"] == "unsupported"]
    out += _table(rows, ["Term", "Name", "Reason"])
    out += ["", "## All Business Terms"]
    for (title, _), start, end in zip(AREAS, starts, starts[1:] + [len(order)]):
        rows = [
            [f"`{term}`", terms[term]["name"], SHOWN[terms[term]["disposition"]], _details(terms[term])]
            for term in order[start:end]
        ]
        out += ["", f"### {title}", ""] + _table(rows, ["Term", "Name", "invoice-pro", "Details"])
    return "\n".join(out)


def _docs_span(text):
    """(start, end) of the generated part between the markers, or None."""
    start, end = text.find(DOCS_BEGIN), text.find(DOCS_END)
    if start < 0 or end < start:
        return None
    return start + len(DOCS_BEGIN), end


def docs_problems(table, path=DOCS):
    """The problems of the documentation: the generated part is missing or
    not the one of `table`."""
    text = Path(path).read_text(encoding="utf-8")
    span = _docs_span(text)
    if span is None:
        return [f"{path}: the markers of the business-term tables are missing"]
    if text[span[0]:span[1]].strip() != docs_block(table):
        return [f"{path}: the business-term tables differ from the table (run bt_disposition.py --update-docs)"]
    return []


def update_docs(table, path=DOCS):
    """Rewrites the generated part of the documentation."""
    text = Path(path).read_text(encoding="utf-8")
    span = _docs_span(text)
    if span is None:
        raise ValueError(f"{path}: the markers of the business-term tables are missing")
    Path(path).write_text(text[: span[0]] + "\n\n" + docs_block(table) + "\n\n" + text[span[1]:], encoding="utf-8")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("table", nargs="?", default=str(TABLE), help="default: tools/zugferd/bt-disposition.toml")
    ap.add_argument("--docs", default=str(DOCS), help="default: docs/docs/e-invoicing/invoice-data/business-terms.md")
    ap.add_argument("--update-docs", action="store_true", help="rewrite the business-term tables of the documentation")
    args = ap.parse_args(argv)
    try:
        table = load(args.table)
    except (OSError, tomllib.TOMLDecodeError) as e:
        print(f"✘ {args.table}: {e}")
        return 1
    problems = check(table)
    if problems:
        for problem in problems:
            print(f"  {problem}")
        print(f"✘ {len(problems)} problems in {args.table}: every business term of EN 16931 needs a disposition.")
        return 1
    try:
        if args.update_docs:
            update_docs(table, args.docs)
        problems = docs_problems(table, args.docs)
    except (OSError, ValueError) as e:
        problems = [str(e)]
    if problems:
        for problem in problems:
            print(f"✘ {problem}")
        return 1
    summary = ", ".join(f"{name} {count}" for name, count in sorted(counts(table).items()))
    print(f"✔ {len(TERMS)} business terms of EN 16931 have a disposition ({summary}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
