#!/usr/bin/env python3
"""Performance gate of the e-invoice path (CI).

  gate.py [--runs 5] [--sizes 5,50,300] [--nightly] [--plain-limit-ms MS]
          [--yellow-fails] [--json FILE]

Compiles benchmark invoices with and without e-invoice (German seller and
buyer, `zugferd: auto`, i.e. XRechnung, DIN 5008 theme) with `typst compile
--timings` and computes, per size, the median over the runs of

  share = time in e-invoice code (zf compile) / total time (plain compile)

"Time in e-invoice code" is every trace event of a file under src/zugferd/
that is not nested in another one: the module import plus `process-zugferd`
(and the report in "report" mode). Traces vary by a few percent, wall-clock
times by far more, so the gate is based on traces (concept, section 6.5).

Thresholds (concept 6.5)
  RED     share > 25 % at any size; share > 15 % at 50 or 300 lines;
          nightly: e-invoice time (1000 lines) / (300 lines) > 4 (linearity);
          --plain-limit-ms: a plain invoice spends more than this in
          e-invoice code (the modules must only load when `zugferd` is set)
  YELLOW  share > 15 % at 5 lines (blocks a release, not a PR; --yellow-fails
          turns it red); component budgets: module import > 12 ms,
          serializer > 0.5 ms per line

Exit status: 1 when a threshold is red, 0 otherwise.

The benchmark invoices and the trace aggregation come from the performance
tools next to this script (gen_bench.py, trace_agg.py) when they exist;
otherwise from equivalent built-in versions below.
"""

import argparse
import json
import os
import re
import statistics
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(HERE))

RED_ANY = 25.0
RED_LARGE = 15.0
LARGE_SIZES = (50, 300)
YELLOW_SMALL = 15.0
SMALL_SIZES = (5,)
LINEARITY_MAX = 4.0
IMPORT_BUDGET_MS = 12.0
SERIALIZER_BUDGET_MS_PER_LINE = 0.5
EINVOICE_PREFIX = "/src/zugferd/"

# ---------------------------------------------------------------- benchmark and trace aggregation

try:  # the benchmark generator of the performance tools
    from gen_bench import render as bench_render
except ImportError:
    _BENCH_HEAD = """// Generated by tools/perf/gate.py, do not edit.
#import "/src/lib.typ": *
#show: invoice.with(
  theme: themes.DIN-5008(),
  zugferd: {zugferd},
  sender: (
    name: "Consulting Group GmbH",
    address: "Tech Avenue 42",
    city: "80331 München",
    country: country.de,
    tax-nr: "143/123/45678",
    vat-id: "DE123456789",
    contact: (name: "Max Mustermann", phone: "+49 89 1234567", email: "max@consultinggroup.de"),
  ),
  recipient: (
    name: "Acme Corp",
    address: "Industrial Road 1",
    city: (name: "Stuttgart", post-code: "70173"),
    country: country.de,
    vat-id: "DE987654321",
    buyer-reference: "DE123456789-12345-12",
  ),
  invoice-nr: "INV-2026-102",
  date: datetime(year: 2026, month: 7, day: 8),
  tax: tax.vat(19%),
)
#line-items[
"""
    _BENCH_TAIL = """]
#payment-goal(days: 14)
#bank-details(bank: "Global Business Bank", iban: "DE89370400440532013000", bic: "GBBADEFFXXX")
"""

    def bench_render(kind, lines, zugferd):
        """Basic benchmark (kind "b"): one VAT rate, net prices."""
        assert kind == "b", "the built-in benchmark has only the basic kind"
        items = "".join(
            f"  #item([Position {i} with a longer description text], quantity: {i % 7 + 1}, "
            f"unit: unit.hour, price: {10 + (i * 37) % 400}.{i % 100:02d})\n"
            for i in range(lines)
        )
        return _BENCH_HEAD.format(zugferd=zugferd) + items + _BENCH_TAIL


try:  # the trace aggregation of the performance tools
    from trace_agg import aggregate, load_events
except ImportError:

    def load_events(path):
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, list) else data["traceEvents"]

    def aggregate(events, prefix=EINVOICE_PREFIX):
        """Total time and time in e-invoice code (outermost events of files
        under `prefix`), in microseconds, plus the inclusive time per key."""
        stack, open_keys, inclusive = [], {}, {}
        depth, einvoice, einvoice_import = 0, 0.0, 0.0
        for event in events:
            if event["ph"] == "B":
                args = event.get("args") or {}
                key = event["name"]
                if key in ("func call", "eval", "context", "for loop"):
                    key = f'{key} {args.get("file")}:{args.get("line")}'
                mine = (args.get("file") or "").startswith(prefix)
                stack.append((key, event["ts"], mine, event["name"]))
                open_keys[key] = open_keys.get(key, 0) + 1
                depth += mine
            elif event["ph"] == "E":
                key, start, mine, name = stack.pop()
                duration = event["ts"] - start
                open_keys[key] -= 1
                if open_keys[key] == 0:
                    inclusive[key] = inclusive.get(key, 0.0) + duration
                if mine:
                    depth -= 1
                    if depth == 0:
                        einvoice += duration
                        einvoice_import += duration if name == "eval" else 0.0
        total = inclusive.get("compile once") or inclusive.get("compile") or 0.0
        return {"total": total, "einvoice": einvoice, "einvoice_import": einvoice_import, "inclusive": inclusive}


def function_key(relative_file, name):
    """Trace key of calls of the function `name` defined in `relative_file`
    (a call is recorded with the line of the definition), or None."""
    path = REPO / relative_file
    if not path.exists():
        return None
    for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if re.match(rf"^#let {re.escape(name)}\(", line):
            return f"func call /{relative_file}:{number}"
    return None


# ---------------------------------------------------------------- measuring


def compile_traced(typst, document, out_dir):
    trace = out_dir / (document.stem + ".json")
    cmd = [typst, "compile", "--root", str(REPO), "--timings", str(trace), str(document), str(out_dir / (document.stem + ".pdf"))]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise SystemExit(f"compilation failed: {document}\n{proc.stderr}")
    return aggregate(load_events(trace))


def measure(sizes, runs, typst, out_dir):
    bench = out_dir / "bench"
    bench.mkdir(parents=True, exist_ok=True)
    documents = []
    for n in sizes:
        for variant, zugferd in (("plain", "none"), ("zf", "auto")):
            path = bench / f"b-{n}-{variant}.typ"
            path.write_text(bench_render("b", n, zugferd), encoding="utf-8")
            documents.append((n, variant, path))
    serializer = function_key("src/zugferd/xml.typ", "dict-to-xml")
    samples = {(n, v): [] for n, v, _ in documents}
    for _, _, path in documents:  # warm-up: file cache, fonts, packages
        compile_traced(typst, path, out_dir)
    for _ in range(runs):  # round-robin, so that load drifts hit all alike
        for n, variant, path in documents:
            result = compile_traced(typst, path, out_dir)
            samples[(n, variant)].append(
                {
                    "total": result["total"] / 1000,
                    "einvoice": result["einvoice"] / 1000,
                    "import": result["einvoice_import"] / 1000,
                    "serializer": result["inclusive"].get(serializer, 0.0) / 1000 if serializer else None,
                }
            )
    rows = []
    for n in sizes:
        plain, zf = samples[(n, "plain")], samples[(n, "zf")]

        def med(values, key):
            data = [v[key] for v in values if v[key] is not None]
            return statistics.median(data) if data else None

        row = {
            "lines": n,
            "plain_total_ms": med(plain, "total"),
            "zf_total_ms": med(zf, "total"),
            "einvoice_ms": med(zf, "einvoice"),
            "import_ms": med(zf, "import"),
            "serializer_ms": med(zf, "serializer"),
            "plain_einvoice_ms": med(plain, "einvoice"),
        }
        row["share_pct"] = 100 * row["einvoice_ms"] / row["plain_total_ms"]
        row["total_diff_pct"] = 100 * (row["zf_total_ms"] / row["plain_total_ms"] - 1)
        rows.append(row)
    return rows


# ---------------------------------------------------------------- verdict


def verdict(rows, plain_limit_ms, yellow_fails):
    red, yellow = [], []
    for row in rows:
        n, share = row["lines"], row["share_pct"]
        if share > RED_ANY:
            red.append(f"{n} lines: e-invoice share {share:.1f} % exceeds the hard ceiling of {RED_ANY:g} %")
        elif n in LARGE_SIZES and share > RED_LARGE:
            red.append(f"{n} lines: e-invoice share {share:.1f} % exceeds the target of {RED_LARGE:g} %")
        elif n in SMALL_SIZES and share > YELLOW_SMALL:
            (red if yellow_fails else yellow).append(
                f"{n} lines: e-invoice share {share:.1f} % exceeds the target of {YELLOW_SMALL:g} %"
            )
        if row["import_ms"] is not None and row["import_ms"] > IMPORT_BUDGET_MS:
            yellow.append(f"{n} lines: module import {row['import_ms']:.1f} ms exceeds its budget of {IMPORT_BUDGET_MS:g} ms")
        if row["serializer_ms"] and row["serializer_ms"] / n > SERIALIZER_BUDGET_MS_PER_LINE and n >= 50:
            yellow.append(
                f"{n} lines: serializer {row['serializer_ms'] / n:.2f} ms per line exceeds its budget of "
                f"{SERIALIZER_BUDGET_MS_PER_LINE:g} ms"
            )
        if plain_limit_ms is not None and row["plain_einvoice_ms"] > plain_limit_ms:
            red.append(
                f"{n} lines: the plain invoice spends {row['plain_einvoice_ms']:.1f} ms in e-invoice code "
                f"(limit {plain_limit_ms:g} ms): the modules must only load when `zugferd` is set"
            )
    by_size = {row["lines"]: row for row in rows}
    if 300 in by_size and 1000 in by_size:
        ratio = by_size[1000]["einvoice_ms"] / by_size[300]["einvoice_ms"]
        if ratio > LINEARITY_MAX:
            red.append(f"e-invoice time 1000 / 300 lines = {ratio:.2f} > {LINEARITY_MAX:g}: the path grows faster than linearly")
    return red, yellow


def table(rows):
    out = [
        "| lines | plain | e-invoice | share | import | serializer/line | plain in e-invoice code | zf vs plain |",
        "|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for r in rows:
        ser = f"{r['serializer_ms'] / r['lines']:.2f} ms" if r["serializer_ms"] else "-"
        out.append(
            f"| {r['lines']} | {r['plain_total_ms']:.1f} ms | {r['einvoice_ms']:.1f} ms | **{r['share_pct']:.1f} %** "
            f"| {r['import_ms']:.1f} ms | {ser} | {r['plain_einvoice_ms']:.1f} ms | {r['total_diff_pct']:+.1f} % |"
        )
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--runs", type=int, default=5, help="traced compiles per document (median)")
    ap.add_argument("--sizes", default="5,50,300", help="line counts of the benchmark invoices")
    ap.add_argument("--nightly", action="store_true", help="also 1000 lines and the linearity check")
    ap.add_argument("--plain-limit-ms", type=float, default=None,
                    help="red when a plain invoice spends more than this in e-invoice code")
    ap.add_argument("--yellow-fails", action="store_true", help="treat yellow as red (release gate)")
    ap.add_argument("--json", default=None, help="write the measurements to this file")
    ap.add_argument("--out", default=None, help="work directory (default: <repo>/build/perf)")
    args = ap.parse_args(argv)
    typst = os.environ.get("TYPST_BIN") or "typst"
    sizes = [int(s) for s in args.sizes.split(",") if s]
    if args.nightly and 1000 not in sizes:
        sizes.append(1000)
    out_dir = Path(args.out) if args.out else REPO / "build" / "perf"
    out_dir.mkdir(parents=True, exist_ok=True)
    started = time.perf_counter()
    version = subprocess.run([typst, "--version"], capture_output=True, text=True).stdout.strip()
    rows = measure(sizes, args.runs, typst, out_dir)
    red, yellow = verdict(rows, args.plain_limit_ms, args.yellow_fails)
    status = "RED" if red else "YELLOW" if yellow else "GREEN"
    text = [
        f"E-invoice performance gate: {status}  ({version}, trace, median of {args.runs} runs, "
        f"{time.perf_counter() - started:.0f} s)",
        "",
        table(rows),
        "",
        "share = time in e-invoice code of the zf compile / total time of the plain compile "
        f"(red > {RED_ANY:g} % at any size or > {RED_LARGE:g} % at 50/300 lines, yellow > {YELLOW_SMALL:g} % at 5 lines)",
    ]
    text += [f"RED: {m}" for m in red] + [f"YELLOW: {m}" for m in yellow]
    print("\n".join(text))
    if os.environ.get("GITHUB_ACTIONS"):
        for m in red:
            print(f"::error title=E-invoice performance::{m}")
        for m in yellow:
            print(f"::warning title=E-invoice performance::{m}")
    summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary:
        with open(summary, "a", encoding="utf-8") as f:
            f.write("## E-invoice performance gate\n\n" + "\n".join(text) + "\n")
    if args.json:
        Path(args.json).write_text(json.dumps({"status": status, "red": red, "yellow": yellow, "rows": rows}, indent=2))
    return 1 if red else 0


if __name__ == "__main__":
    sys.exit(main())
