name: Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Flake Checks (Pre-commit)
        run: nix build .#checks.x86_64-linux.lint --print-build-logs
