name: Publish to Typst Universe

on:
  release:
    types: [published]

jobs:
  publish:
    # Use the shared workflow from this repo
    uses: leonieziechmann/typst-nix-utils/.github/workflows/publish-package.yaml@main
    with:
      # Target fork where the PR branch will be pushed
      fork_repo: leonieziechmann/packages
      files: "typst.toml README.md LICENSE thumbnail.png src template images"
    secrets:
      # A PAT with permission to push to your fork
      packages_pat: ${{ secrets.PACKAGES_PAT }}
