name: Release Package Archive

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  archive-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: typ-flow
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Create Package Archive
        run: nix build --accept-flake-config .#release

      - name: Upload Asset to Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          files: result/*.tar.gz
