name: Release Package Archive

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  archive-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: typ-flow
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Create Package Archive
        run: nix build --accept-flake-config .#release

      - name: Upload Asset to Release
        uses: softprops/action-gh-release@v1
        with:
          files: result/*.tar.gz
