name: Testing
on:
  push:
    branches: [ main ]
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'lib.typ'
      - 'src/**'
      - 'tests/**'
      - 'template/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'lib.typ'
      - 'src/**'
      - 'tests/**'
      - 'template/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: typ-flow
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run test suite
        run: nix develop --accept-flake-config --command tt run

      - name: Archive artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
        if: always()
        with:
          name: artifacts
          path: |
            tests/**/diff/*.png
            tests/**/out/*.png
            tests/**/ref/*.png
          retention-days: 5
