// The code lists the data model reads (src/zugferd/model.typ): the codes of
// the lists of the validation (`validator` of guard/lists.typ, generated by
// tools/zugferd/gen_guard.py), as arrays. The rules look codes up in the
// lists themselves (`in-list` of rules/engine.typ), which needs no array.

#import "guard/lists.typ": validator as _lists

/// The ISO 3166-1 alpha-2 country codes of EN 16931 (BR-CL-14): the codes
/// of every validation of the profiles based on EN 16931, without South
/// Sudan ("SS") and the withdrawn "AN".
#let countries = _lists.country.every.trim().split(" ")

/// The UN/ECE Recommendation 20 and 21 unit codes (BT-130, BT-150;
/// BR-CL-23).
#let units = _lists.unit.every.trim().split(" ")
