// Code lists of the validator, generated by tools/zugferd/gen_guard.py.

/// Per name and kind, a string of codes between spaces: `every` (in all lists),
/// `factur-x`, `xrechnung`, and `newer`/`withdrawn` (newest EN 16931 list).
///
/// -> dictionary
#let lists = {
  let out = (:)
  for (name, kinds) in json("code-lists.json") {
    if name == "generated" { continue }
    let every = " " + kinds.every.join(" ") + " "
    let entry = (:)
    for (kind, lines) in kinds {
      let codes = if lines == () { "" } else { lines.join(" ") + " " }
      // `factur-x` and `xrechnung` hold the codes they have beyond `every`.
      let base = if kind in ("factur-x", "xrechnung") { every } else { " " }
      entry.insert(kind, base + codes)
    }
    out.insert(name, entry)
  }
  out
}
